// This file is generated by gen_props.go. DO NOT EDIT.

package segment

type gbProp byte

const (
	gbPropCR                    = gbProp(iota)
	gbPropControl               = gbProp(iota)
	gbPropExtend                = gbProp(iota)
	gbPropExtended_Pictographic = gbProp(iota)
	gbPropL                     = gbProp(iota)
	gbPropLF                    = gbProp(iota)
	gbPropLV                    = gbProp(iota)
	gbPropLVT                   = gbProp(iota)
	gbPropOther                 = gbProp(iota)
	gbPropPrepend               = gbProp(iota)
	gbPropRegional_Indicator    = gbProp(iota)
	gbPropSpacingMark           = gbProp(iota)
	gbPropT                     = gbProp(iota)
	gbPropV                     = gbProp(iota)
	gbPropZWJ                   = gbProp(iota)
)

func gbPropForRune(r rune) gbProp {
	switch {

	case r <= 9:
		return gbPropControl

	case r <= 10:
		return gbPropLF

	case r <= 12:
		return gbPropControl

	case r <= 13:
		return gbPropCR

	case r <= 31:
		return gbPropControl

	case r <= 126:
		return gbPropOther

	case r <= 159:
		return gbPropControl

	case r <= 168:
		return gbPropOther

	case r <= 169:
		return gbPropExtended_Pictographic

	case r <= 172:
		return gbPropOther

	case r <= 173:
		return gbPropControl

	case r <= 174:
		return gbPropExtended_Pictographic

	case r <= 767:
		return gbPropOther

	case r <= 879:
		return gbPropExtend

	case r <= 1154:
		return gbPropOther

	case r <= 1159:
		return gbPropExtend

	case r <= 1161:
		return gbPropExtend

	case r <= 1424:
		return gbPropOther

	case r <= 1469:
		return gbPropExtend

	case r <= 1470:
		return gbPropOther

	case r <= 1471:
		return gbPropExtend

	case r <= 1472:
		return gbPropOther

	case r <= 1474:
		return gbPropExtend

	case r <= 1475:
		return gbPropOther

	case r <= 1477:
		return gbPropExtend

	case r <= 1478:
		return gbPropOther

	case r <= 1479:
		return gbPropExtend

	case r <= 1535:
		return gbPropOther

	case r <= 1541:
		return gbPropPrepend

	case r <= 1551:
		return gbPropOther

	case r <= 1562:
		return gbPropExtend

	case r <= 1563:
		return gbPropOther

	case r <= 1564:
		return gbPropControl

	case r <= 1610:
		return gbPropOther

	case r <= 1631:
		return gbPropExtend

	case r <= 1647:
		return gbPropOther

	case r <= 1648:
		return gbPropExtend

	case r <= 1749:
		return gbPropOther

	case r <= 1756:
		return gbPropExtend

	case r <= 1757:
		return gbPropPrepend

	case r <= 1758:
		return gbPropOther

	case r <= 1764:
		return gbPropExtend

	case r <= 1766:
		return gbPropOther

	case r <= 1768:
		return gbPropExtend

	case r <= 1769:
		return gbPropOther

	case r <= 1773:
		return gbPropExtend

	case r <= 1806:
		return gbPropOther

	case r <= 1807:
		return gbPropPrepend

	case r <= 1808:
		return gbPropOther

	case r <= 1809:
		return gbPropExtend

	case r <= 1839:
		return gbPropOther

	case r <= 1866:
		return gbPropExtend

	case r <= 1957:
		return gbPropOther

	case r <= 1968:
		return gbPropExtend

	case r <= 2026:
		return gbPropOther

	case r <= 2035:
		return gbPropExtend

	case r <= 2044:
		return gbPropOther

	case r <= 2045:
		return gbPropExtend

	case r <= 2069:
		return gbPropOther

	case r <= 2073:
		return gbPropExtend

	case r <= 2074:
		return gbPropOther

	case r <= 2083:
		return gbPropExtend

	case r <= 2084:
		return gbPropOther

	case r <= 2087:
		return gbPropExtend

	case r <= 2088:
		return gbPropOther

	case r <= 2093:
		return gbPropExtend

	case r <= 2136:
		return gbPropOther

	case r <= 2139:
		return gbPropExtend

	case r <= 2258:
		return gbPropOther

	case r <= 2273:
		return gbPropExtend

	case r <= 2274:
		return gbPropPrepend

	case r <= 2306:
		return gbPropExtend

	case r <= 2307:
		return gbPropSpacingMark

	case r <= 2361:
		return gbPropOther

	case r <= 2362:
		return gbPropExtend

	case r <= 2363:
		return gbPropSpacingMark

	case r <= 2364:
		return gbPropExtend

	case r <= 2365:
		return gbPropOther

	case r <= 2368:
		return gbPropSpacingMark

	case r <= 2376:
		return gbPropExtend

	case r <= 2380:
		return gbPropSpacingMark

	case r <= 2381:
		return gbPropExtend

	case r <= 2383:
		return gbPropSpacingMark

	case r <= 2384:
		return gbPropOther

	case r <= 2391:
		return gbPropExtend

	case r <= 2401:
		return gbPropOther

	case r <= 2403:
		return gbPropExtend

	case r <= 2432:
		return gbPropOther

	case r <= 2433:
		return gbPropExtend

	case r <= 2435:
		return gbPropSpacingMark

	case r <= 2491:
		return gbPropOther

	case r <= 2492:
		return gbPropExtend

	case r <= 2493:
		return gbPropOther

	case r <= 2494:
		return gbPropExtend

	case r <= 2496:
		return gbPropSpacingMark

	case r <= 2500:
		return gbPropExtend

	case r <= 2502:
		return gbPropOther

	case r <= 2504:
		return gbPropSpacingMark

	case r <= 2506:
		return gbPropOther

	case r <= 2508:
		return gbPropSpacingMark

	case r <= 2509:
		return gbPropExtend

	case r <= 2518:
		return gbPropOther

	case r <= 2519:
		return gbPropExtend

	case r <= 2529:
		return gbPropOther

	case r <= 2531:
		return gbPropExtend

	case r <= 2557:
		return gbPropOther

	case r <= 2558:
		return gbPropExtend

	case r <= 2560:
		return gbPropOther

	case r <= 2562:
		return gbPropExtend

	case r <= 2563:
		return gbPropSpacingMark

	case r <= 2619:
		return gbPropOther

	case r <= 2620:
		return gbPropExtend

	case r <= 2621:
		return gbPropOther

	case r <= 2624:
		return gbPropSpacingMark

	case r <= 2626:
		return gbPropExtend

	case r <= 2630:
		return gbPropOther

	case r <= 2632:
		return gbPropExtend

	case r <= 2634:
		return gbPropOther

	case r <= 2637:
		return gbPropExtend

	case r <= 2640:
		return gbPropOther

	case r <= 2641:
		return gbPropExtend

	case r <= 2671:
		return gbPropOther

	case r <= 2673:
		return gbPropExtend

	case r <= 2676:
		return gbPropOther

	case r <= 2677:
		return gbPropExtend

	case r <= 2688:
		return gbPropOther

	case r <= 2690:
		return gbPropExtend

	case r <= 2691:
		return gbPropSpacingMark

	case r <= 2747:
		return gbPropOther

	case r <= 2748:
		return gbPropExtend

	case r <= 2749:
		return gbPropOther

	case r <= 2752:
		return gbPropSpacingMark

	case r <= 2757:
		return gbPropExtend

	case r <= 2758:
		return gbPropOther

	case r <= 2760:
		return gbPropExtend

	case r <= 2761:
		return gbPropSpacingMark

	case r <= 2762:
		return gbPropOther

	case r <= 2764:
		return gbPropSpacingMark

	case r <= 2765:
		return gbPropExtend

	case r <= 2785:
		return gbPropOther

	case r <= 2787:
		return gbPropExtend

	case r <= 2809:
		return gbPropOther

	case r <= 2815:
		return gbPropExtend

	case r <= 2816:
		return gbPropOther

	case r <= 2817:
		return gbPropExtend

	case r <= 2819:
		return gbPropSpacingMark

	case r <= 2875:
		return gbPropOther

	case r <= 2876:
		return gbPropExtend

	case r <= 2877:
		return gbPropOther

	case r <= 2878:
		return gbPropExtend

	case r <= 2879:
		return gbPropExtend

	case r <= 2880:
		return gbPropSpacingMark

	case r <= 2884:
		return gbPropExtend

	case r <= 2886:
		return gbPropOther

	case r <= 2888:
		return gbPropSpacingMark

	case r <= 2890:
		return gbPropOther

	case r <= 2892:
		return gbPropSpacingMark

	case r <= 2893:
		return gbPropExtend

	case r <= 2900:
		return gbPropOther

	case r <= 2902:
		return gbPropExtend

	case r <= 2903:
		return gbPropExtend

	case r <= 2913:
		return gbPropOther

	case r <= 2915:
		return gbPropExtend

	case r <= 2945:
		return gbPropOther

	case r <= 2946:
		return gbPropExtend

	case r <= 3005:
		return gbPropOther

	case r <= 3006:
		return gbPropExtend

	case r <= 3007:
		return gbPropSpacingMark

	case r <= 3008:
		return gbPropExtend

	case r <= 3010:
		return gbPropSpacingMark

	case r <= 3013:
		return gbPropOther

	case r <= 3016:
		return gbPropSpacingMark

	case r <= 3017:
		return gbPropOther

	case r <= 3020:
		return gbPropSpacingMark

	case r <= 3021:
		return gbPropExtend

	case r <= 3030:
		return gbPropOther

	case r <= 3031:
		return gbPropExtend

	case r <= 3071:
		return gbPropOther

	case r <= 3072:
		return gbPropExtend

	case r <= 3075:
		return gbPropSpacingMark

	case r <= 3076:
		return gbPropExtend

	case r <= 3133:
		return gbPropOther

	case r <= 3136:
		return gbPropExtend

	case r <= 3140:
		return gbPropSpacingMark

	case r <= 3141:
		return gbPropOther

	case r <= 3144:
		return gbPropExtend

	case r <= 3145:
		return gbPropOther

	case r <= 3149:
		return gbPropExtend

	case r <= 3156:
		return gbPropOther

	case r <= 3158:
		return gbPropExtend

	case r <= 3169:
		return gbPropOther

	case r <= 3171:
		return gbPropExtend

	case r <= 3200:
		return gbPropOther

	case r <= 3201:
		return gbPropExtend

	case r <= 3203:
		return gbPropSpacingMark

	case r <= 3259:
		return gbPropOther

	case r <= 3260:
		return gbPropExtend

	case r <= 3261:
		return gbPropOther

	case r <= 3262:
		return gbPropSpacingMark

	case r <= 3263:
		return gbPropExtend

	case r <= 3265:
		return gbPropSpacingMark

	case r <= 3266:
		return gbPropExtend

	case r <= 3268:
		return gbPropSpacingMark

	case r <= 3269:
		return gbPropOther

	case r <= 3270:
		return gbPropExtend

	case r <= 3272:
		return gbPropSpacingMark

	case r <= 3273:
		return gbPropOther

	case r <= 3275:
		return gbPropSpacingMark

	case r <= 3277:
		return gbPropExtend

	case r <= 3284:
		return gbPropOther

	case r <= 3286:
		return gbPropExtend

	case r <= 3297:
		return gbPropOther

	case r <= 3299:
		return gbPropExtend

	case r <= 3327:
		return gbPropOther

	case r <= 3329:
		return gbPropExtend

	case r <= 3331:
		return gbPropSpacingMark

	case r <= 3386:
		return gbPropOther

	case r <= 3388:
		return gbPropExtend

	case r <= 3389:
		return gbPropOther

	case r <= 3390:
		return gbPropExtend

	case r <= 3392:
		return gbPropSpacingMark

	case r <= 3396:
		return gbPropExtend

	case r <= 3397:
		return gbPropOther

	case r <= 3400:
		return gbPropSpacingMark

	case r <= 3401:
		return gbPropOther

	case r <= 3404:
		return gbPropSpacingMark

	case r <= 3405:
		return gbPropExtend

	case r <= 3406:
		return gbPropPrepend

	case r <= 3414:
		return gbPropOther

	case r <= 3415:
		return gbPropExtend

	case r <= 3425:
		return gbPropOther

	case r <= 3427:
		return gbPropExtend

	case r <= 3456:
		return gbPropOther

	case r <= 3457:
		return gbPropExtend

	case r <= 3459:
		return gbPropSpacingMark

	case r <= 3529:
		return gbPropOther

	case r <= 3530:
		return gbPropExtend

	case r <= 3534:
		return gbPropOther

	case r <= 3535:
		return gbPropExtend

	case r <= 3537:
		return gbPropSpacingMark

	case r <= 3540:
		return gbPropExtend

	case r <= 3541:
		return gbPropOther

	case r <= 3542:
		return gbPropExtend

	case r <= 3543:
		return gbPropOther

	case r <= 3550:
		return gbPropSpacingMark

	case r <= 3551:
		return gbPropExtend

	case r <= 3569:
		return gbPropOther

	case r <= 3571:
		return gbPropSpacingMark

	case r <= 3632:
		return gbPropOther

	case r <= 3633:
		return gbPropExtend

	case r <= 3634:
		return gbPropOther

	case r <= 3635:
		return gbPropSpacingMark

	case r <= 3642:
		return gbPropExtend

	case r <= 3654:
		return gbPropOther

	case r <= 3662:
		return gbPropExtend

	case r <= 3760:
		return gbPropOther

	case r <= 3761:
		return gbPropExtend

	case r <= 3762:
		return gbPropOther

	case r <= 3763:
		return gbPropSpacingMark

	case r <= 3772:
		return gbPropExtend

	case r <= 3783:
		return gbPropOther

	case r <= 3789:
		return gbPropExtend

	case r <= 3863:
		return gbPropOther

	case r <= 3865:
		return gbPropExtend

	case r <= 3892:
		return gbPropOther

	case r <= 3893:
		return gbPropExtend

	case r <= 3894:
		return gbPropOther

	case r <= 3895:
		return gbPropExtend

	case r <= 3896:
		return gbPropOther

	case r <= 3897:
		return gbPropExtend

	case r <= 3901:
		return gbPropOther

	case r <= 3903:
		return gbPropSpacingMark

	case r <= 3952:
		return gbPropOther

	case r <= 3966:
		return gbPropExtend

	case r <= 3967:
		return gbPropSpacingMark

	case r <= 3972:
		return gbPropExtend

	case r <= 3973:
		return gbPropOther

	case r <= 3975:
		return gbPropExtend

	case r <= 3980:
		return gbPropOther

	case r <= 3991:
		return gbPropExtend

	case r <= 3992:
		return gbPropOther

	case r <= 4028:
		return gbPropExtend

	case r <= 4037:
		return gbPropOther

	case r <= 4038:
		return gbPropExtend

	case r <= 4140:
		return gbPropOther

	case r <= 4144:
		return gbPropExtend

	case r <= 4145:
		return gbPropSpacingMark

	case r <= 4151:
		return gbPropExtend

	case r <= 4152:
		return gbPropOther

	case r <= 4154:
		return gbPropExtend

	case r <= 4156:
		return gbPropSpacingMark

	case r <= 4158:
		return gbPropExtend

	case r <= 4181:
		return gbPropOther

	case r <= 4183:
		return gbPropSpacingMark

	case r <= 4185:
		return gbPropExtend

	case r <= 4189:
		return gbPropOther

	case r <= 4192:
		return gbPropExtend

	case r <= 4208:
		return gbPropOther

	case r <= 4212:
		return gbPropExtend

	case r <= 4225:
		return gbPropOther

	case r <= 4226:
		return gbPropExtend

	case r <= 4227:
		return gbPropOther

	case r <= 4228:
		return gbPropSpacingMark

	case r <= 4230:
		return gbPropExtend

	case r <= 4236:
		return gbPropOther

	case r <= 4237:
		return gbPropExtend

	case r <= 4252:
		return gbPropOther

	case r <= 4253:
		return gbPropExtend

	case r <= 4351:
		return gbPropOther

	case r <= 4447:
		return gbPropL

	case r <= 4519:
		return gbPropV

	case r <= 4607:
		return gbPropT

	case r <= 4956:
		return gbPropOther

	case r <= 4959:
		return gbPropExtend

	case r <= 5905:
		return gbPropOther

	case r <= 5908:
		return gbPropExtend

	case r <= 5937:
		return gbPropOther

	case r <= 5940:
		return gbPropExtend

	case r <= 5969:
		return gbPropOther

	case r <= 5971:
		return gbPropExtend

	case r <= 6001:
		return gbPropOther

	case r <= 6003:
		return gbPropExtend

	case r <= 6067:
		return gbPropOther

	case r <= 6069:
		return gbPropExtend

	case r <= 6070:
		return gbPropSpacingMark

	case r <= 6077:
		return gbPropExtend

	case r <= 6085:
		return gbPropSpacingMark

	case r <= 6086:
		return gbPropExtend

	case r <= 6088:
		return gbPropSpacingMark

	case r <= 6099:
		return gbPropExtend

	case r <= 6108:
		return gbPropOther

	case r <= 6109:
		return gbPropExtend

	case r <= 6154:
		return gbPropOther

	case r <= 6157:
		return gbPropExtend

	case r <= 6158:
		return gbPropControl

	case r <= 6276:
		return gbPropOther

	case r <= 6278:
		return gbPropExtend

	case r <= 6312:
		return gbPropOther

	case r <= 6313:
		return gbPropExtend

	case r <= 6431:
		return gbPropOther

	case r <= 6434:
		return gbPropExtend

	case r <= 6438:
		return gbPropSpacingMark

	case r <= 6440:
		return gbPropExtend

	case r <= 6443:
		return gbPropSpacingMark

	case r <= 6447:
		return gbPropOther

	case r <= 6449:
		return gbPropSpacingMark

	case r <= 6450:
		return gbPropExtend

	case r <= 6456:
		return gbPropSpacingMark

	case r <= 6459:
		return gbPropExtend

	case r <= 6678:
		return gbPropOther

	case r <= 6680:
		return gbPropExtend

	case r <= 6682:
		return gbPropSpacingMark

	case r <= 6683:
		return gbPropExtend

	case r <= 6740:
		return gbPropOther

	case r <= 6741:
		return gbPropSpacingMark

	case r <= 6742:
		return gbPropExtend

	case r <= 6743:
		return gbPropSpacingMark

	case r <= 6750:
		return gbPropExtend

	case r <= 6751:
		return gbPropOther

	case r <= 6752:
		return gbPropExtend

	case r <= 6753:
		return gbPropOther

	case r <= 6754:
		return gbPropExtend

	case r <= 6756:
		return gbPropOther

	case r <= 6764:
		return gbPropExtend

	case r <= 6770:
		return gbPropSpacingMark

	case r <= 6780:
		return gbPropExtend

	case r <= 6782:
		return gbPropOther

	case r <= 6783:
		return gbPropExtend

	case r <= 6831:
		return gbPropOther

	case r <= 6845:
		return gbPropExtend

	case r <= 6846:
		return gbPropExtend

	case r <= 6848:
		return gbPropExtend

	case r <= 6911:
		return gbPropOther

	case r <= 6915:
		return gbPropExtend

	case r <= 6916:
		return gbPropSpacingMark

	case r <= 6963:
		return gbPropOther

	case r <= 6964:
		return gbPropExtend

	case r <= 6965:
		return gbPropExtend

	case r <= 6970:
		return gbPropExtend

	case r <= 6971:
		return gbPropSpacingMark

	case r <= 6972:
		return gbPropExtend

	case r <= 6977:
		return gbPropSpacingMark

	case r <= 6978:
		return gbPropExtend

	case r <= 6980:
		return gbPropSpacingMark

	case r <= 7018:
		return gbPropOther

	case r <= 7027:
		return gbPropExtend

	case r <= 7039:
		return gbPropOther

	case r <= 7041:
		return gbPropExtend

	case r <= 7042:
		return gbPropSpacingMark

	case r <= 7072:
		return gbPropOther

	case r <= 7073:
		return gbPropSpacingMark

	case r <= 7077:
		return gbPropExtend

	case r <= 7079:
		return gbPropSpacingMark

	case r <= 7081:
		return gbPropExtend

	case r <= 7082:
		return gbPropSpacingMark

	case r <= 7085:
		return gbPropExtend

	case r <= 7141:
		return gbPropOther

	case r <= 7142:
		return gbPropExtend

	case r <= 7143:
		return gbPropSpacingMark

	case r <= 7145:
		return gbPropExtend

	case r <= 7148:
		return gbPropSpacingMark

	case r <= 7149:
		return gbPropExtend

	case r <= 7150:
		return gbPropSpacingMark

	case r <= 7153:
		return gbPropExtend

	case r <= 7155:
		return gbPropSpacingMark

	case r <= 7203:
		return gbPropOther

	case r <= 7211:
		return gbPropSpacingMark

	case r <= 7219:
		return gbPropExtend

	case r <= 7221:
		return gbPropSpacingMark

	case r <= 7223:
		return gbPropExtend

	case r <= 7375:
		return gbPropOther

	case r <= 7378:
		return gbPropExtend

	case r <= 7379:
		return gbPropOther

	case r <= 7392:
		return gbPropExtend

	case r <= 7393:
		return gbPropSpacingMark

	case r <= 7400:
		return gbPropExtend

	case r <= 7404:
		return gbPropOther

	case r <= 7405:
		return gbPropExtend

	case r <= 7411:
		return gbPropOther

	case r <= 7412:
		return gbPropExtend

	case r <= 7414:
		return gbPropOther

	case r <= 7415:
		return gbPropSpacingMark

	case r <= 7417:
		return gbPropExtend

	case r <= 7615:
		return gbPropOther

	case r <= 7673:
		return gbPropExtend

	case r <= 7674:
		return gbPropOther

	case r <= 7679:
		return gbPropExtend

	case r <= 8202:
		return gbPropOther

	case r <= 8203:
		return gbPropControl

	case r <= 8204:
		return gbPropExtend

	case r <= 8205:
		return gbPropZWJ

	case r <= 8207:
		return gbPropControl

	case r <= 8231:
		return gbPropOther

	case r <= 8232:
		return gbPropControl

	case r <= 8233:
		return gbPropControl

	case r <= 8238:
		return gbPropControl

	case r <= 8251:
		return gbPropOther

	case r <= 8252:
		return gbPropExtended_Pictographic

	case r <= 8264:
		return gbPropOther

	case r <= 8265:
		return gbPropExtended_Pictographic

	case r <= 8287:
		return gbPropOther

	case r <= 8292:
		return gbPropControl

	case r <= 8293:
		return gbPropControl

	case r <= 8303:
		return gbPropControl

	case r <= 8399:
		return gbPropOther

	case r <= 8412:
		return gbPropExtend

	case r <= 8416:
		return gbPropExtend

	case r <= 8417:
		return gbPropExtend

	case r <= 8420:
		return gbPropExtend

	case r <= 8432:
		return gbPropExtend

	case r <= 8481:
		return gbPropOther

	case r <= 8482:
		return gbPropExtended_Pictographic

	case r <= 8504:
		return gbPropOther

	case r <= 8505:
		return gbPropExtended_Pictographic

	case r <= 8595:
		return gbPropOther

	case r <= 8601:
		return gbPropExtended_Pictographic

	case r <= 8616:
		return gbPropOther

	case r <= 8618:
		return gbPropExtended_Pictographic

	case r <= 8985:
		return gbPropOther

	case r <= 8987:
		return gbPropExtended_Pictographic

	case r <= 8999:
		return gbPropOther

	case r <= 9000:
		return gbPropExtended_Pictographic

	case r <= 9095:
		return gbPropOther

	case r <= 9096:
		return gbPropExtended_Pictographic

	case r <= 9166:
		return gbPropOther

	case r <= 9167:
		return gbPropExtended_Pictographic

	case r <= 9192:
		return gbPropOther

	case r <= 9203:
		return gbPropExtended_Pictographic

	case r <= 9207:
		return gbPropOther

	case r <= 9210:
		return gbPropExtended_Pictographic

	case r <= 9409:
		return gbPropOther

	case r <= 9410:
		return gbPropExtended_Pictographic

	case r <= 9641:
		return gbPropOther

	case r <= 9643:
		return gbPropExtended_Pictographic

	case r <= 9653:
		return gbPropOther

	case r <= 9654:
		return gbPropExtended_Pictographic

	case r <= 9663:
		return gbPropOther

	case r <= 9664:
		return gbPropExtended_Pictographic

	case r <= 9722:
		return gbPropOther

	case r <= 9726:
		return gbPropExtended_Pictographic

	case r <= 9727:
		return gbPropOther

	case r <= 9732:
		return gbPropExtended_Pictographic

	case r <= 9733:
		return gbPropExtended_Pictographic

	case r <= 9734:
		return gbPropOther

	case r <= 9741:
		return gbPropExtended_Pictographic

	case r <= 9742:
		return gbPropExtended_Pictographic

	case r <= 9744:
		return gbPropExtended_Pictographic

	case r <= 9745:
		return gbPropExtended_Pictographic

	case r <= 9746:
		return gbPropExtended_Pictographic

	case r <= 9747:
		return gbPropOther

	case r <= 9749:
		return gbPropExtended_Pictographic

	case r <= 9751:
		return gbPropExtended_Pictographic

	case r <= 9752:
		return gbPropExtended_Pictographic

	case r <= 9756:
		return gbPropExtended_Pictographic

	case r <= 9757:
		return gbPropExtended_Pictographic

	case r <= 9759:
		return gbPropExtended_Pictographic

	case r <= 9760:
		return gbPropExtended_Pictographic

	case r <= 9761:
		return gbPropExtended_Pictographic

	case r <= 9763:
		return gbPropExtended_Pictographic

	case r <= 9765:
		return gbPropExtended_Pictographic

	case r <= 9766:
		return gbPropExtended_Pictographic

	case r <= 9769:
		return gbPropExtended_Pictographic

	case r <= 9770:
		return gbPropExtended_Pictographic

	case r <= 9773:
		return gbPropExtended_Pictographic

	case r <= 9775:
		return gbPropExtended_Pictographic

	case r <= 9783:
		return gbPropExtended_Pictographic

	case r <= 9786:
		return gbPropExtended_Pictographic

	case r <= 9791:
		return gbPropExtended_Pictographic

	case r <= 9792:
		return gbPropExtended_Pictographic

	case r <= 9793:
		return gbPropExtended_Pictographic

	case r <= 9794:
		return gbPropExtended_Pictographic

	case r <= 9799:
		return gbPropExtended_Pictographic

	case r <= 9811:
		return gbPropExtended_Pictographic

	case r <= 9822:
		return gbPropExtended_Pictographic

	case r <= 9823:
		return gbPropExtended_Pictographic

	case r <= 9824:
		return gbPropExtended_Pictographic

	case r <= 9826:
		return gbPropExtended_Pictographic

	case r <= 9827:
		return gbPropExtended_Pictographic

	case r <= 9828:
		return gbPropExtended_Pictographic

	case r <= 9830:
		return gbPropExtended_Pictographic

	case r <= 9831:
		return gbPropExtended_Pictographic

	case r <= 9832:
		return gbPropExtended_Pictographic

	case r <= 9850:
		return gbPropExtended_Pictographic

	case r <= 9851:
		return gbPropExtended_Pictographic

	case r <= 9853:
		return gbPropExtended_Pictographic

	case r <= 9854:
		return gbPropExtended_Pictographic

	case r <= 9855:
		return gbPropExtended_Pictographic

	case r <= 9861:
		return gbPropExtended_Pictographic

	case r <= 9871:
		return gbPropOther

	case r <= 9873:
		return gbPropExtended_Pictographic

	case r <= 9876:
		return gbPropExtended_Pictographic

	case r <= 9877:
		return gbPropExtended_Pictographic

	case r <= 9879:
		return gbPropExtended_Pictographic

	case r <= 9880:
		return gbPropExtended_Pictographic

	case r <= 9881:
		return gbPropExtended_Pictographic

	case r <= 9882:
		return gbPropExtended_Pictographic

	case r <= 9884:
		return gbPropExtended_Pictographic

	case r <= 9887:
		return gbPropExtended_Pictographic

	case r <= 9889:
		return gbPropExtended_Pictographic

	case r <= 9897:
		return gbPropExtended_Pictographic

	case r <= 9899:
		return gbPropExtended_Pictographic

	case r <= 9903:
		return gbPropExtended_Pictographic

	case r <= 9905:
		return gbPropExtended_Pictographic

	case r <= 9916:
		return gbPropExtended_Pictographic

	case r <= 9918:
		return gbPropExtended_Pictographic

	case r <= 9923:
		return gbPropExtended_Pictographic

	case r <= 9925:
		return gbPropExtended_Pictographic

	case r <= 9927:
		return gbPropExtended_Pictographic

	case r <= 9928:
		return gbPropExtended_Pictographic

	case r <= 9933:
		return gbPropExtended_Pictographic

	case r <= 9935:
		return gbPropExtended_Pictographic

	case r <= 9936:
		return gbPropExtended_Pictographic

	case r <= 9937:
		return gbPropExtended_Pictographic

	case r <= 9938:
		return gbPropExtended_Pictographic

	case r <= 9940:
		return gbPropExtended_Pictographic

	case r <= 9960:
		return gbPropExtended_Pictographic

	case r <= 9962:
		return gbPropExtended_Pictographic

	case r <= 9967:
		return gbPropExtended_Pictographic

	case r <= 9973:
		return gbPropExtended_Pictographic

	case r <= 9974:
		return gbPropExtended_Pictographic

	case r <= 9978:
		return gbPropExtended_Pictographic

	case r <= 9980:
		return gbPropExtended_Pictographic

	case r <= 9981:
		return gbPropExtended_Pictographic

	case r <= 9985:
		return gbPropExtended_Pictographic

	case r <= 9986:
		return gbPropExtended_Pictographic

	case r <= 9988:
		return gbPropExtended_Pictographic

	case r <= 9989:
		return gbPropExtended_Pictographic

	case r <= 9991:
		return gbPropOther

	case r <= 9997:
		return gbPropExtended_Pictographic

	case r <= 9998:
		return gbPropExtended_Pictographic

	case r <= 9999:
		return gbPropExtended_Pictographic

	case r <= 10001:
		return gbPropExtended_Pictographic

	case r <= 10002:
		return gbPropExtended_Pictographic

	case r <= 10003:
		return gbPropOther

	case r <= 10004:
		return gbPropExtended_Pictographic

	case r <= 10005:
		return gbPropOther

	case r <= 10006:
		return gbPropExtended_Pictographic

	case r <= 10012:
		return gbPropOther

	case r <= 10013:
		return gbPropExtended_Pictographic

	case r <= 10016:
		return gbPropOther

	case r <= 10017:
		return gbPropExtended_Pictographic

	case r <= 10023:
		return gbPropOther

	case r <= 10024:
		return gbPropExtended_Pictographic

	case r <= 10034:
		return gbPropOther

	case r <= 10036:
		return gbPropExtended_Pictographic

	case r <= 10051:
		return gbPropOther

	case r <= 10052:
		return gbPropExtended_Pictographic

	case r <= 10054:
		return gbPropOther

	case r <= 10055:
		return gbPropExtended_Pictographic

	case r <= 10059:
		return gbPropOther

	case r <= 10060:
		return gbPropExtended_Pictographic

	case r <= 10061:
		return gbPropOther

	case r <= 10062:
		return gbPropExtended_Pictographic

	case r <= 10066:
		return gbPropOther

	case r <= 10069:
		return gbPropExtended_Pictographic

	case r <= 10070:
		return gbPropOther

	case r <= 10071:
		return gbPropExtended_Pictographic

	case r <= 10082:
		return gbPropOther

	case r <= 10084:
		return gbPropExtended_Pictographic

	case r <= 10087:
		return gbPropExtended_Pictographic

	case r <= 10132:
		return gbPropOther

	case r <= 10135:
		return gbPropExtended_Pictographic

	case r <= 10144:
		return gbPropOther

	case r <= 10145:
		return gbPropExtended_Pictographic

	case r <= 10159:
		return gbPropOther

	case r <= 10160:
		return gbPropExtended_Pictographic

	case r <= 10174:
		return gbPropOther

	case r <= 10175:
		return gbPropExtended_Pictographic

	case r <= 10547:
		return gbPropOther

	case r <= 10549:
		return gbPropExtended_Pictographic

	case r <= 11012:
		return gbPropOther

	case r <= 11015:
		return gbPropExtended_Pictographic

	case r <= 11034:
		return gbPropOther

	case r <= 11036:
		return gbPropExtended_Pictographic

	case r <= 11087:
		return gbPropOther

	case r <= 11088:
		return gbPropExtended_Pictographic

	case r <= 11092:
		return gbPropOther

	case r <= 11093:
		return gbPropExtended_Pictographic

	case r <= 11502:
		return gbPropOther

	case r <= 11505:
		return gbPropExtend

	case r <= 11646:
		return gbPropOther

	case r <= 11647:
		return gbPropExtend

	case r <= 11743:
		return gbPropOther

	case r <= 11775:
		return gbPropExtend

	case r <= 12329:
		return gbPropOther

	case r <= 12333:
		return gbPropExtend

	case r <= 12335:
		return gbPropExtend

	case r <= 12336:
		return gbPropExtended_Pictographic

	case r <= 12348:
		return gbPropOther

	case r <= 12349:
		return gbPropExtended_Pictographic

	case r <= 12440:
		return gbPropOther

	case r <= 12442:
		return gbPropExtend

	case r <= 12950:
		return gbPropOther

	case r <= 12951:
		return gbPropExtended_Pictographic

	case r <= 12952:
		return gbPropOther

	case r <= 12953:
		return gbPropExtended_Pictographic

	case r <= 42606:
		return gbPropOther

	case r <= 42607:
		return gbPropExtend

	case r <= 42610:
		return gbPropExtend

	case r <= 42611:
		return gbPropOther

	case r <= 42621:
		return gbPropExtend

	case r <= 42653:
		return gbPropOther

	case r <= 42655:
		return gbPropExtend

	case r <= 42735:
		return gbPropOther

	case r <= 42737:
		return gbPropExtend

	case r <= 43009:
		return gbPropOther

	case r <= 43010:
		return gbPropExtend

	case r <= 43013:
		return gbPropOther

	case r <= 43014:
		return gbPropExtend

	case r <= 43018:
		return gbPropOther

	case r <= 43019:
		return gbPropExtend

	case r <= 43042:
		return gbPropOther

	case r <= 43044:
		return gbPropSpacingMark

	case r <= 43046:
		return gbPropExtend

	case r <= 43047:
		return gbPropSpacingMark

	case r <= 43051:
		return gbPropOther

	case r <= 43052:
		return gbPropExtend

	case r <= 43135:
		return gbPropOther

	case r <= 43137:
		return gbPropSpacingMark

	case r <= 43187:
		return gbPropOther

	case r <= 43203:
		return gbPropSpacingMark

	case r <= 43205:
		return gbPropExtend

	case r <= 43231:
		return gbPropOther

	case r <= 43249:
		return gbPropExtend

	case r <= 43262:
		return gbPropOther

	case r <= 43263:
		return gbPropExtend

	case r <= 43301:
		return gbPropOther

	case r <= 43309:
		return gbPropExtend

	case r <= 43334:
		return gbPropOther

	case r <= 43345:
		return gbPropExtend

	case r <= 43347:
		return gbPropSpacingMark

	case r <= 43359:
		return gbPropOther

	case r <= 43388:
		return gbPropL

	case r <= 43391:
		return gbPropOther

	case r <= 43394:
		return gbPropExtend

	case r <= 43395:
		return gbPropSpacingMark

	case r <= 43442:
		return gbPropOther

	case r <= 43443:
		return gbPropExtend

	case r <= 43445:
		return gbPropSpacingMark

	case r <= 43449:
		return gbPropExtend

	case r <= 43451:
		return gbPropSpacingMark

	case r <= 43453:
		return gbPropExtend

	case r <= 43456:
		return gbPropSpacingMark

	case r <= 43492:
		return gbPropOther

	case r <= 43493:
		return gbPropExtend

	case r <= 43560:
		return gbPropOther

	case r <= 43566:
		return gbPropExtend

	case r <= 43568:
		return gbPropSpacingMark

	case r <= 43570:
		return gbPropExtend

	case r <= 43572:
		return gbPropSpacingMark

	case r <= 43574:
		return gbPropExtend

	case r <= 43586:
		return gbPropOther

	case r <= 43587:
		return gbPropExtend

	case r <= 43595:
		return gbPropOther

	case r <= 43596:
		return gbPropExtend

	case r <= 43597:
		return gbPropSpacingMark

	case r <= 43643:
		return gbPropOther

	case r <= 43644:
		return gbPropExtend

	case r <= 43695:
		return gbPropOther

	case r <= 43696:
		return gbPropExtend

	case r <= 43697:
		return gbPropOther

	case r <= 43700:
		return gbPropExtend

	case r <= 43702:
		return gbPropOther

	case r <= 43704:
		return gbPropExtend

	case r <= 43709:
		return gbPropOther

	case r <= 43711:
		return gbPropExtend

	case r <= 43712:
		return gbPropOther

	case r <= 43713:
		return gbPropExtend

	case r <= 43754:
		return gbPropOther

	case r <= 43755:
		return gbPropSpacingMark

	case r <= 43757:
		return gbPropExtend

	case r <= 43759:
		return gbPropSpacingMark

	case r <= 43764:
		return gbPropOther

	case r <= 43765:
		return gbPropSpacingMark

	case r <= 43766:
		return gbPropExtend

	case r <= 44002:
		return gbPropOther

	case r <= 44004:
		return gbPropSpacingMark

	case r <= 44005:
		return gbPropExtend

	case r <= 44007:
		return gbPropSpacingMark

	case r <= 44008:
		return gbPropExtend

	case r <= 44010:
		return gbPropSpacingMark

	case r <= 44011:
		return gbPropOther

	case r <= 44012:
		return gbPropSpacingMark

	case r <= 44013:
		return gbPropExtend

	case r <= 44031:
		return gbPropOther

	case r <= 44032:
		return gbPropLV

	case r <= 44059:
		return gbPropLVT

	case r <= 44060:
		return gbPropLV

	case r <= 44087:
		return gbPropLVT

	case r <= 44088:
		return gbPropLV

	case r <= 44115:
		return gbPropLVT

	case r <= 44116:
		return gbPropLV

	case r <= 44143:
		return gbPropLVT

	case r <= 44144:
		return gbPropLV

	case r <= 44171:
		return gbPropLVT

	case r <= 44172:
		return gbPropLV

	case r <= 44199:
		return gbPropLVT

	case r <= 44200:
		return gbPropLV

	case r <= 44227:
		return gbPropLVT

	case r <= 44228:
		return gbPropLV

	case r <= 44255:
		return gbPropLVT

	case r <= 44256:
		return gbPropLV

	case r <= 44283:
		return gbPropLVT

	case r <= 44284:
		return gbPropLV

	case r <= 44311:
		return gbPropLVT

	case r <= 44312:
		return gbPropLV

	case r <= 44339:
		return gbPropLVT

	case r <= 44340:
		return gbPropLV

	case r <= 44367:
		return gbPropLVT

	case r <= 44368:
		return gbPropLV

	case r <= 44395:
		return gbPropLVT

	case r <= 44396:
		return gbPropLV

	case r <= 44423:
		return gbPropLVT

	case r <= 44424:
		return gbPropLV

	case r <= 44451:
		return gbPropLVT

	case r <= 44452:
		return gbPropLV

	case r <= 44479:
		return gbPropLVT

	case r <= 44480:
		return gbPropLV

	case r <= 44507:
		return gbPropLVT

	case r <= 44508:
		return gbPropLV

	case r <= 44535:
		return gbPropLVT

	case r <= 44536:
		return gbPropLV

	case r <= 44563:
		return gbPropLVT

	case r <= 44564:
		return gbPropLV

	case r <= 44591:
		return gbPropLVT

	case r <= 44592:
		return gbPropLV

	case r <= 44619:
		return gbPropLVT

	case r <= 44620:
		return gbPropLV

	case r <= 44647:
		return gbPropLVT

	case r <= 44648:
		return gbPropLV

	case r <= 44675:
		return gbPropLVT

	case r <= 44676:
		return gbPropLV

	case r <= 44703:
		return gbPropLVT

	case r <= 44704:
		return gbPropLV

	case r <= 44731:
		return gbPropLVT

	case r <= 44732:
		return gbPropLV

	case r <= 44759:
		return gbPropLVT

	case r <= 44760:
		return gbPropLV

	case r <= 44787:
		return gbPropLVT

	case r <= 44788:
		return gbPropLV

	case r <= 44815:
		return gbPropLVT

	case r <= 44816:
		return gbPropLV

	case r <= 44843:
		return gbPropLVT

	case r <= 44844:
		return gbPropLV

	case r <= 44871:
		return gbPropLVT

	case r <= 44872:
		return gbPropLV

	case r <= 44899:
		return gbPropLVT

	case r <= 44900:
		return gbPropLV

	case r <= 44927:
		return gbPropLVT

	case r <= 44928:
		return gbPropLV

	case r <= 44955:
		return gbPropLVT

	case r <= 44956:
		return gbPropLV

	case r <= 44983:
		return gbPropLVT

	case r <= 44984:
		return gbPropLV

	case r <= 45011:
		return gbPropLVT

	case r <= 45012:
		return gbPropLV

	case r <= 45039:
		return gbPropLVT

	case r <= 45040:
		return gbPropLV

	case r <= 45067:
		return gbPropLVT

	case r <= 45068:
		return gbPropLV

	case r <= 45095:
		return gbPropLVT

	case r <= 45096:
		return gbPropLV

	case r <= 45123:
		return gbPropLVT

	case r <= 45124:
		return gbPropLV

	case r <= 45151:
		return gbPropLVT

	case r <= 45152:
		return gbPropLV

	case r <= 45179:
		return gbPropLVT

	case r <= 45180:
		return gbPropLV

	case r <= 45207:
		return gbPropLVT

	case r <= 45208:
		return gbPropLV

	case r <= 45235:
		return gbPropLVT

	case r <= 45236:
		return gbPropLV

	case r <= 45263:
		return gbPropLVT

	case r <= 45264:
		return gbPropLV

	case r <= 45291:
		return gbPropLVT

	case r <= 45292:
		return gbPropLV

	case r <= 45319:
		return gbPropLVT

	case r <= 45320:
		return gbPropLV

	case r <= 45347:
		return gbPropLVT

	case r <= 45348:
		return gbPropLV

	case r <= 45375:
		return gbPropLVT

	case r <= 45376:
		return gbPropLV

	case r <= 45403:
		return gbPropLVT

	case r <= 45404:
		return gbPropLV

	case r <= 45431:
		return gbPropLVT

	case r <= 45432:
		return gbPropLV

	case r <= 45459:
		return gbPropLVT

	case r <= 45460:
		return gbPropLV

	case r <= 45487:
		return gbPropLVT

	case r <= 45488:
		return gbPropLV

	case r <= 45515:
		return gbPropLVT

	case r <= 45516:
		return gbPropLV

	case r <= 45543:
		return gbPropLVT

	case r <= 45544:
		return gbPropLV

	case r <= 45571:
		return gbPropLVT

	case r <= 45572:
		return gbPropLV

	case r <= 45599:
		return gbPropLVT

	case r <= 45600:
		return gbPropLV

	case r <= 45627:
		return gbPropLVT

	case r <= 45628:
		return gbPropLV

	case r <= 45655:
		return gbPropLVT

	case r <= 45656:
		return gbPropLV

	case r <= 45683:
		return gbPropLVT

	case r <= 45684:
		return gbPropLV

	case r <= 45711:
		return gbPropLVT

	case r <= 45712:
		return gbPropLV

	case r <= 45739:
		return gbPropLVT

	case r <= 45740:
		return gbPropLV

	case r <= 45767:
		return gbPropLVT

	case r <= 45768:
		return gbPropLV

	case r <= 45795:
		return gbPropLVT

	case r <= 45796:
		return gbPropLV

	case r <= 45823:
		return gbPropLVT

	case r <= 45824:
		return gbPropLV

	case r <= 45851:
		return gbPropLVT

	case r <= 45852:
		return gbPropLV

	case r <= 45879:
		return gbPropLVT

	case r <= 45880:
		return gbPropLV

	case r <= 45907:
		return gbPropLVT

	case r <= 45908:
		return gbPropLV

	case r <= 45935:
		return gbPropLVT

	case r <= 45936:
		return gbPropLV

	case r <= 45963:
		return gbPropLVT

	case r <= 45964:
		return gbPropLV

	case r <= 45991:
		return gbPropLVT

	case r <= 45992:
		return gbPropLV

	case r <= 46019:
		return gbPropLVT

	case r <= 46020:
		return gbPropLV

	case r <= 46047:
		return gbPropLVT

	case r <= 46048:
		return gbPropLV

	case r <= 46075:
		return gbPropLVT

	case r <= 46076:
		return gbPropLV

	case r <= 46103:
		return gbPropLVT

	case r <= 46104:
		return gbPropLV

	case r <= 46131:
		return gbPropLVT

	case r <= 46132:
		return gbPropLV

	case r <= 46159:
		return gbPropLVT

	case r <= 46160:
		return gbPropLV

	case r <= 46187:
		return gbPropLVT

	case r <= 46188:
		return gbPropLV

	case r <= 46215:
		return gbPropLVT

	case r <= 46216:
		return gbPropLV

	case r <= 46243:
		return gbPropLVT

	case r <= 46244:
		return gbPropLV

	case r <= 46271:
		return gbPropLVT

	case r <= 46272:
		return gbPropLV

	case r <= 46299:
		return gbPropLVT

	case r <= 46300:
		return gbPropLV

	case r <= 46327:
		return gbPropLVT

	case r <= 46328:
		return gbPropLV

	case r <= 46355:
		return gbPropLVT

	case r <= 46356:
		return gbPropLV

	case r <= 46383:
		return gbPropLVT

	case r <= 46384:
		return gbPropLV

	case r <= 46411:
		return gbPropLVT

	case r <= 46412:
		return gbPropLV

	case r <= 46439:
		return gbPropLVT

	case r <= 46440:
		return gbPropLV

	case r <= 46467:
		return gbPropLVT

	case r <= 46468:
		return gbPropLV

	case r <= 46495:
		return gbPropLVT

	case r <= 46496:
		return gbPropLV

	case r <= 46523:
		return gbPropLVT

	case r <= 46524:
		return gbPropLV

	case r <= 46551:
		return gbPropLVT

	case r <= 46552:
		return gbPropLV

	case r <= 46579:
		return gbPropLVT

	case r <= 46580:
		return gbPropLV

	case r <= 46607:
		return gbPropLVT

	case r <= 46608:
		return gbPropLV

	case r <= 46635:
		return gbPropLVT

	case r <= 46636:
		return gbPropLV

	case r <= 46663:
		return gbPropLVT

	case r <= 46664:
		return gbPropLV

	case r <= 46691:
		return gbPropLVT

	case r <= 46692:
		return gbPropLV

	case r <= 46719:
		return gbPropLVT

	case r <= 46720:
		return gbPropLV

	case r <= 46747:
		return gbPropLVT

	case r <= 46748:
		return gbPropLV

	case r <= 46775:
		return gbPropLVT

	case r <= 46776:
		return gbPropLV

	case r <= 46803:
		return gbPropLVT

	case r <= 46804:
		return gbPropLV

	case r <= 46831:
		return gbPropLVT

	case r <= 46832:
		return gbPropLV

	case r <= 46859:
		return gbPropLVT

	case r <= 46860:
		return gbPropLV

	case r <= 46887:
		return gbPropLVT

	case r <= 46888:
		return gbPropLV

	case r <= 46915:
		return gbPropLVT

	case r <= 46916:
		return gbPropLV

	case r <= 46943:
		return gbPropLVT

	case r <= 46944:
		return gbPropLV

	case r <= 46971:
		return gbPropLVT

	case r <= 46972:
		return gbPropLV

	case r <= 46999:
		return gbPropLVT

	case r <= 47000:
		return gbPropLV

	case r <= 47027:
		return gbPropLVT

	case r <= 47028:
		return gbPropLV

	case r <= 47055:
		return gbPropLVT

	case r <= 47056:
		return gbPropLV

	case r <= 47083:
		return gbPropLVT

	case r <= 47084:
		return gbPropLV

	case r <= 47111:
		return gbPropLVT

	case r <= 47112:
		return gbPropLV

	case r <= 47139:
		return gbPropLVT

	case r <= 47140:
		return gbPropLV

	case r <= 47167:
		return gbPropLVT

	case r <= 47168:
		return gbPropLV

	case r <= 47195:
		return gbPropLVT

	case r <= 47196:
		return gbPropLV

	case r <= 47223:
		return gbPropLVT

	case r <= 47224:
		return gbPropLV

	case r <= 47251:
		return gbPropLVT

	case r <= 47252:
		return gbPropLV

	case r <= 47279:
		return gbPropLVT

	case r <= 47280:
		return gbPropLV

	case r <= 47307:
		return gbPropLVT

	case r <= 47308:
		return gbPropLV

	case r <= 47335:
		return gbPropLVT

	case r <= 47336:
		return gbPropLV

	case r <= 47363:
		return gbPropLVT

	case r <= 47364:
		return gbPropLV

	case r <= 47391:
		return gbPropLVT

	case r <= 47392:
		return gbPropLV

	case r <= 47419:
		return gbPropLVT

	case r <= 47420:
		return gbPropLV

	case r <= 47447:
		return gbPropLVT

	case r <= 47448:
		return gbPropLV

	case r <= 47475:
		return gbPropLVT

	case r <= 47476:
		return gbPropLV

	case r <= 47503:
		return gbPropLVT

	case r <= 47504:
		return gbPropLV

	case r <= 47531:
		return gbPropLVT

	case r <= 47532:
		return gbPropLV

	case r <= 47559:
		return gbPropLVT

	case r <= 47560:
		return gbPropLV

	case r <= 47587:
		return gbPropLVT

	case r <= 47588:
		return gbPropLV

	case r <= 47615:
		return gbPropLVT

	case r <= 47616:
		return gbPropLV

	case r <= 47643:
		return gbPropLVT

	case r <= 47644:
		return gbPropLV

	case r <= 47671:
		return gbPropLVT

	case r <= 47672:
		return gbPropLV

	case r <= 47699:
		return gbPropLVT

	case r <= 47700:
		return gbPropLV

	case r <= 47727:
		return gbPropLVT

	case r <= 47728:
		return gbPropLV

	case r <= 47755:
		return gbPropLVT

	case r <= 47756:
		return gbPropLV

	case r <= 47783:
		return gbPropLVT

	case r <= 47784:
		return gbPropLV

	case r <= 47811:
		return gbPropLVT

	case r <= 47812:
		return gbPropLV

	case r <= 47839:
		return gbPropLVT

	case r <= 47840:
		return gbPropLV

	case r <= 47867:
		return gbPropLVT

	case r <= 47868:
		return gbPropLV

	case r <= 47895:
		return gbPropLVT

	case r <= 47896:
		return gbPropLV

	case r <= 47923:
		return gbPropLVT

	case r <= 47924:
		return gbPropLV

	case r <= 47951:
		return gbPropLVT

	case r <= 47952:
		return gbPropLV

	case r <= 47979:
		return gbPropLVT

	case r <= 47980:
		return gbPropLV

	case r <= 48007:
		return gbPropLVT

	case r <= 48008:
		return gbPropLV

	case r <= 48035:
		return gbPropLVT

	case r <= 48036:
		return gbPropLV

	case r <= 48063:
		return gbPropLVT

	case r <= 48064:
		return gbPropLV

	case r <= 48091:
		return gbPropLVT

	case r <= 48092:
		return gbPropLV

	case r <= 48119:
		return gbPropLVT

	case r <= 48120:
		return gbPropLV

	case r <= 48147:
		return gbPropLVT

	case r <= 48148:
		return gbPropLV

	case r <= 48175:
		return gbPropLVT

	case r <= 48176:
		return gbPropLV

	case r <= 48203:
		return gbPropLVT

	case r <= 48204:
		return gbPropLV

	case r <= 48231:
		return gbPropLVT

	case r <= 48232:
		return gbPropLV

	case r <= 48259:
		return gbPropLVT

	case r <= 48260:
		return gbPropLV

	case r <= 48287:
		return gbPropLVT

	case r <= 48288:
		return gbPropLV

	case r <= 48315:
		return gbPropLVT

	case r <= 48316:
		return gbPropLV

	case r <= 48343:
		return gbPropLVT

	case r <= 48344:
		return gbPropLV

	case r <= 48371:
		return gbPropLVT

	case r <= 48372:
		return gbPropLV

	case r <= 48399:
		return gbPropLVT

	case r <= 48400:
		return gbPropLV

	case r <= 48427:
		return gbPropLVT

	case r <= 48428:
		return gbPropLV

	case r <= 48455:
		return gbPropLVT

	case r <= 48456:
		return gbPropLV

	case r <= 48483:
		return gbPropLVT

	case r <= 48484:
		return gbPropLV

	case r <= 48511:
		return gbPropLVT

	case r <= 48512:
		return gbPropLV

	case r <= 48539:
		return gbPropLVT

	case r <= 48540:
		return gbPropLV

	case r <= 48567:
		return gbPropLVT

	case r <= 48568:
		return gbPropLV

	case r <= 48595:
		return gbPropLVT

	case r <= 48596:
		return gbPropLV

	case r <= 48623:
		return gbPropLVT

	case r <= 48624:
		return gbPropLV

	case r <= 48651:
		return gbPropLVT

	case r <= 48652:
		return gbPropLV

	case r <= 48679:
		return gbPropLVT

	case r <= 48680:
		return gbPropLV

	case r <= 48707:
		return gbPropLVT

	case r <= 48708:
		return gbPropLV

	case r <= 48735:
		return gbPropLVT

	case r <= 48736:
		return gbPropLV

	case r <= 48763:
		return gbPropLVT

	case r <= 48764:
		return gbPropLV

	case r <= 48791:
		return gbPropLVT

	case r <= 48792:
		return gbPropLV

	case r <= 48819:
		return gbPropLVT

	case r <= 48820:
		return gbPropLV

	case r <= 48847:
		return gbPropLVT

	case r <= 48848:
		return gbPropLV

	case r <= 48875:
		return gbPropLVT

	case r <= 48876:
		return gbPropLV

	case r <= 48903:
		return gbPropLVT

	case r <= 48904:
		return gbPropLV

	case r <= 48931:
		return gbPropLVT

	case r <= 48932:
		return gbPropLV

	case r <= 48959:
		return gbPropLVT

	case r <= 48960:
		return gbPropLV

	case r <= 48987:
		return gbPropLVT

	case r <= 48988:
		return gbPropLV

	case r <= 49015:
		return gbPropLVT

	case r <= 49016:
		return gbPropLV

	case r <= 49043:
		return gbPropLVT

	case r <= 49044:
		return gbPropLV

	case r <= 49071:
		return gbPropLVT

	case r <= 49072:
		return gbPropLV

	case r <= 49099:
		return gbPropLVT

	case r <= 49100:
		return gbPropLV

	case r <= 49127:
		return gbPropLVT

	case r <= 49128:
		return gbPropLV

	case r <= 49155:
		return gbPropLVT

	case r <= 49156:
		return gbPropLV

	case r <= 49183:
		return gbPropLVT

	case r <= 49184:
		return gbPropLV

	case r <= 49211:
		return gbPropLVT

	case r <= 49212:
		return gbPropLV

	case r <= 49239:
		return gbPropLVT

	case r <= 49240:
		return gbPropLV

	case r <= 49267:
		return gbPropLVT

	case r <= 49268:
		return gbPropLV

	case r <= 49295:
		return gbPropLVT

	case r <= 49296:
		return gbPropLV

	case r <= 49323:
		return gbPropLVT

	case r <= 49324:
		return gbPropLV

	case r <= 49351:
		return gbPropLVT

	case r <= 49352:
		return gbPropLV

	case r <= 49379:
		return gbPropLVT

	case r <= 49380:
		return gbPropLV

	case r <= 49407:
		return gbPropLVT

	case r <= 49408:
		return gbPropLV

	case r <= 49435:
		return gbPropLVT

	case r <= 49436:
		return gbPropLV

	case r <= 49463:
		return gbPropLVT

	case r <= 49464:
		return gbPropLV

	case r <= 49491:
		return gbPropLVT

	case r <= 49492:
		return gbPropLV

	case r <= 49519:
		return gbPropLVT

	case r <= 49520:
		return gbPropLV

	case r <= 49547:
		return gbPropLVT

	case r <= 49548:
		return gbPropLV

	case r <= 49575:
		return gbPropLVT

	case r <= 49576:
		return gbPropLV

	case r <= 49603:
		return gbPropLVT

	case r <= 49604:
		return gbPropLV

	case r <= 49631:
		return gbPropLVT

	case r <= 49632:
		return gbPropLV

	case r <= 49659:
		return gbPropLVT

	case r <= 49660:
		return gbPropLV

	case r <= 49687:
		return gbPropLVT

	case r <= 49688:
		return gbPropLV

	case r <= 49715:
		return gbPropLVT

	case r <= 49716:
		return gbPropLV

	case r <= 49743:
		return gbPropLVT

	case r <= 49744:
		return gbPropLV

	case r <= 49771:
		return gbPropLVT

	case r <= 49772:
		return gbPropLV

	case r <= 49799:
		return gbPropLVT

	case r <= 49800:
		return gbPropLV

	case r <= 49827:
		return gbPropLVT

	case r <= 49828:
		return gbPropLV

	case r <= 49855:
		return gbPropLVT

	case r <= 49856:
		return gbPropLV

	case r <= 49883:
		return gbPropLVT

	case r <= 49884:
		return gbPropLV

	case r <= 49911:
		return gbPropLVT

	case r <= 49912:
		return gbPropLV

	case r <= 49939:
		return gbPropLVT

	case r <= 49940:
		return gbPropLV

	case r <= 49967:
		return gbPropLVT

	case r <= 49968:
		return gbPropLV

	case r <= 49995:
		return gbPropLVT

	case r <= 49996:
		return gbPropLV

	case r <= 50023:
		return gbPropLVT

	case r <= 50024:
		return gbPropLV

	case r <= 50051:
		return gbPropLVT

	case r <= 50052:
		return gbPropLV

	case r <= 50079:
		return gbPropLVT

	case r <= 50080:
		return gbPropLV

	case r <= 50107:
		return gbPropLVT

	case r <= 50108:
		return gbPropLV

	case r <= 50135:
		return gbPropLVT

	case r <= 50136:
		return gbPropLV

	case r <= 50163:
		return gbPropLVT

	case r <= 50164:
		return gbPropLV

	case r <= 50191:
		return gbPropLVT

	case r <= 50192:
		return gbPropLV

	case r <= 50219:
		return gbPropLVT

	case r <= 50220:
		return gbPropLV

	case r <= 50247:
		return gbPropLVT

	case r <= 50248:
		return gbPropLV

	case r <= 50275:
		return gbPropLVT

	case r <= 50276:
		return gbPropLV

	case r <= 50303:
		return gbPropLVT

	case r <= 50304:
		return gbPropLV

	case r <= 50331:
		return gbPropLVT

	case r <= 50332:
		return gbPropLV

	case r <= 50359:
		return gbPropLVT

	case r <= 50360:
		return gbPropLV

	case r <= 50387:
		return gbPropLVT

	case r <= 50388:
		return gbPropLV

	case r <= 50415:
		return gbPropLVT

	case r <= 50416:
		return gbPropLV

	case r <= 50443:
		return gbPropLVT

	case r <= 50444:
		return gbPropLV

	case r <= 50471:
		return gbPropLVT

	case r <= 50472:
		return gbPropLV

	case r <= 50499:
		return gbPropLVT

	case r <= 50500:
		return gbPropLV

	case r <= 50527:
		return gbPropLVT

	case r <= 50528:
		return gbPropLV

	case r <= 50555:
		return gbPropLVT

	case r <= 50556:
		return gbPropLV

	case r <= 50583:
		return gbPropLVT

	case r <= 50584:
		return gbPropLV

	case r <= 50611:
		return gbPropLVT

	case r <= 50612:
		return gbPropLV

	case r <= 50639:
		return gbPropLVT

	case r <= 50640:
		return gbPropLV

	case r <= 50667:
		return gbPropLVT

	case r <= 50668:
		return gbPropLV

	case r <= 50695:
		return gbPropLVT

	case r <= 50696:
		return gbPropLV

	case r <= 50723:
		return gbPropLVT

	case r <= 50724:
		return gbPropLV

	case r <= 50751:
		return gbPropLVT

	case r <= 50752:
		return gbPropLV

	case r <= 50779:
		return gbPropLVT

	case r <= 50780:
		return gbPropLV

	case r <= 50807:
		return gbPropLVT

	case r <= 50808:
		return gbPropLV

	case r <= 50835:
		return gbPropLVT

	case r <= 50836:
		return gbPropLV

	case r <= 50863:
		return gbPropLVT

	case r <= 50864:
		return gbPropLV

	case r <= 50891:
		return gbPropLVT

	case r <= 50892:
		return gbPropLV

	case r <= 50919:
		return gbPropLVT

	case r <= 50920:
		return gbPropLV

	case r <= 50947:
		return gbPropLVT

	case r <= 50948:
		return gbPropLV

	case r <= 50975:
		return gbPropLVT

	case r <= 50976:
		return gbPropLV

	case r <= 51003:
		return gbPropLVT

	case r <= 51004:
		return gbPropLV

	case r <= 51031:
		return gbPropLVT

	case r <= 51032:
		return gbPropLV

	case r <= 51059:
		return gbPropLVT

	case r <= 51060:
		return gbPropLV

	case r <= 51087:
		return gbPropLVT

	case r <= 51088:
		return gbPropLV

	case r <= 51115:
		return gbPropLVT

	case r <= 51116:
		return gbPropLV

	case r <= 51143:
		return gbPropLVT

	case r <= 51144:
		return gbPropLV

	case r <= 51171:
		return gbPropLVT

	case r <= 51172:
		return gbPropLV

	case r <= 51199:
		return gbPropLVT

	case r <= 51200:
		return gbPropLV

	case r <= 51227:
		return gbPropLVT

	case r <= 51228:
		return gbPropLV

	case r <= 51255:
		return gbPropLVT

	case r <= 51256:
		return gbPropLV

	case r <= 51283:
		return gbPropLVT

	case r <= 51284:
		return gbPropLV

	case r <= 51311:
		return gbPropLVT

	case r <= 51312:
		return gbPropLV

	case r <= 51339:
		return gbPropLVT

	case r <= 51340:
		return gbPropLV

	case r <= 51367:
		return gbPropLVT

	case r <= 51368:
		return gbPropLV

	case r <= 51395:
		return gbPropLVT

	case r <= 51396:
		return gbPropLV

	case r <= 51423:
		return gbPropLVT

	case r <= 51424:
		return gbPropLV

	case r <= 51451:
		return gbPropLVT

	case r <= 51452:
		return gbPropLV

	case r <= 51479:
		return gbPropLVT

	case r <= 51480:
		return gbPropLV

	case r <= 51507:
		return gbPropLVT

	case r <= 51508:
		return gbPropLV

	case r <= 51535:
		return gbPropLVT

	case r <= 51536:
		return gbPropLV

	case r <= 51563:
		return gbPropLVT

	case r <= 51564:
		return gbPropLV

	case r <= 51591:
		return gbPropLVT

	case r <= 51592:
		return gbPropLV

	case r <= 51619:
		return gbPropLVT

	case r <= 51620:
		return gbPropLV

	case r <= 51647:
		return gbPropLVT

	case r <= 51648:
		return gbPropLV

	case r <= 51675:
		return gbPropLVT

	case r <= 51676:
		return gbPropLV

	case r <= 51703:
		return gbPropLVT

	case r <= 51704:
		return gbPropLV

	case r <= 51731:
		return gbPropLVT

	case r <= 51732:
		return gbPropLV

	case r <= 51759:
		return gbPropLVT

	case r <= 51760:
		return gbPropLV

	case r <= 51787:
		return gbPropLVT

	case r <= 51788:
		return gbPropLV

	case r <= 51815:
		return gbPropLVT

	case r <= 51816:
		return gbPropLV

	case r <= 51843:
		return gbPropLVT

	case r <= 51844:
		return gbPropLV

	case r <= 51871:
		return gbPropLVT

	case r <= 51872:
		return gbPropLV

	case r <= 51899:
		return gbPropLVT

	case r <= 51900:
		return gbPropLV

	case r <= 51927:
		return gbPropLVT

	case r <= 51928:
		return gbPropLV

	case r <= 51955:
		return gbPropLVT

	case r <= 51956:
		return gbPropLV

	case r <= 51983:
		return gbPropLVT

	case r <= 51984:
		return gbPropLV

	case r <= 52011:
		return gbPropLVT

	case r <= 52012:
		return gbPropLV

	case r <= 52039:
		return gbPropLVT

	case r <= 52040:
		return gbPropLV

	case r <= 52067:
		return gbPropLVT

	case r <= 52068:
		return gbPropLV

	case r <= 52095:
		return gbPropLVT

	case r <= 52096:
		return gbPropLV

	case r <= 52123:
		return gbPropLVT

	case r <= 52124:
		return gbPropLV

	case r <= 52151:
		return gbPropLVT

	case r <= 52152:
		return gbPropLV

	case r <= 52179:
		return gbPropLVT

	case r <= 52180:
		return gbPropLV

	case r <= 52207:
		return gbPropLVT

	case r <= 52208:
		return gbPropLV

	case r <= 52235:
		return gbPropLVT

	case r <= 52236:
		return gbPropLV

	case r <= 52263:
		return gbPropLVT

	case r <= 52264:
		return gbPropLV

	case r <= 52291:
		return gbPropLVT

	case r <= 52292:
		return gbPropLV

	case r <= 52319:
		return gbPropLVT

	case r <= 52320:
		return gbPropLV

	case r <= 52347:
		return gbPropLVT

	case r <= 52348:
		return gbPropLV

	case r <= 52375:
		return gbPropLVT

	case r <= 52376:
		return gbPropLV

	case r <= 52403:
		return gbPropLVT

	case r <= 52404:
		return gbPropLV

	case r <= 52431:
		return gbPropLVT

	case r <= 52432:
		return gbPropLV

	case r <= 52459:
		return gbPropLVT

	case r <= 52460:
		return gbPropLV

	case r <= 52487:
		return gbPropLVT

	case r <= 52488:
		return gbPropLV

	case r <= 52515:
		return gbPropLVT

	case r <= 52516:
		return gbPropLV

	case r <= 52543:
		return gbPropLVT

	case r <= 52544:
		return gbPropLV

	case r <= 52571:
		return gbPropLVT

	case r <= 52572:
		return gbPropLV

	case r <= 52599:
		return gbPropLVT

	case r <= 52600:
		return gbPropLV

	case r <= 52627:
		return gbPropLVT

	case r <= 52628:
		return gbPropLV

	case r <= 52655:
		return gbPropLVT

	case r <= 52656:
		return gbPropLV

	case r <= 52683:
		return gbPropLVT

	case r <= 52684:
		return gbPropLV

	case r <= 52711:
		return gbPropLVT

	case r <= 52712:
		return gbPropLV

	case r <= 52739:
		return gbPropLVT

	case r <= 52740:
		return gbPropLV

	case r <= 52767:
		return gbPropLVT

	case r <= 52768:
		return gbPropLV

	case r <= 52795:
		return gbPropLVT

	case r <= 52796:
		return gbPropLV

	case r <= 52823:
		return gbPropLVT

	case r <= 52824:
		return gbPropLV

	case r <= 52851:
		return gbPropLVT

	case r <= 52852:
		return gbPropLV

	case r <= 52879:
		return gbPropLVT

	case r <= 52880:
		return gbPropLV

	case r <= 52907:
		return gbPropLVT

	case r <= 52908:
		return gbPropLV

	case r <= 52935:
		return gbPropLVT

	case r <= 52936:
		return gbPropLV

	case r <= 52963:
		return gbPropLVT

	case r <= 52964:
		return gbPropLV

	case r <= 52991:
		return gbPropLVT

	case r <= 52992:
		return gbPropLV

	case r <= 53019:
		return gbPropLVT

	case r <= 53020:
		return gbPropLV

	case r <= 53047:
		return gbPropLVT

	case r <= 53048:
		return gbPropLV

	case r <= 53075:
		return gbPropLVT

	case r <= 53076:
		return gbPropLV

	case r <= 53103:
		return gbPropLVT

	case r <= 53104:
		return gbPropLV

	case r <= 53131:
		return gbPropLVT

	case r <= 53132:
		return gbPropLV

	case r <= 53159:
		return gbPropLVT

	case r <= 53160:
		return gbPropLV

	case r <= 53187:
		return gbPropLVT

	case r <= 53188:
		return gbPropLV

	case r <= 53215:
		return gbPropLVT

	case r <= 53216:
		return gbPropLV

	case r <= 53243:
		return gbPropLVT

	case r <= 53244:
		return gbPropLV

	case r <= 53271:
		return gbPropLVT

	case r <= 53272:
		return gbPropLV

	case r <= 53299:
		return gbPropLVT

	case r <= 53300:
		return gbPropLV

	case r <= 53327:
		return gbPropLVT

	case r <= 53328:
		return gbPropLV

	case r <= 53355:
		return gbPropLVT

	case r <= 53356:
		return gbPropLV

	case r <= 53383:
		return gbPropLVT

	case r <= 53384:
		return gbPropLV

	case r <= 53411:
		return gbPropLVT

	case r <= 53412:
		return gbPropLV

	case r <= 53439:
		return gbPropLVT

	case r <= 53440:
		return gbPropLV

	case r <= 53467:
		return gbPropLVT

	case r <= 53468:
		return gbPropLV

	case r <= 53495:
		return gbPropLVT

	case r <= 53496:
		return gbPropLV

	case r <= 53523:
		return gbPropLVT

	case r <= 53524:
		return gbPropLV

	case r <= 53551:
		return gbPropLVT

	case r <= 53552:
		return gbPropLV

	case r <= 53579:
		return gbPropLVT

	case r <= 53580:
		return gbPropLV

	case r <= 53607:
		return gbPropLVT

	case r <= 53608:
		return gbPropLV

	case r <= 53635:
		return gbPropLVT

	case r <= 53636:
		return gbPropLV

	case r <= 53663:
		return gbPropLVT

	case r <= 53664:
		return gbPropLV

	case r <= 53691:
		return gbPropLVT

	case r <= 53692:
		return gbPropLV

	case r <= 53719:
		return gbPropLVT

	case r <= 53720:
		return gbPropLV

	case r <= 53747:
		return gbPropLVT

	case r <= 53748:
		return gbPropLV

	case r <= 53775:
		return gbPropLVT

	case r <= 53776:
		return gbPropLV

	case r <= 53803:
		return gbPropLVT

	case r <= 53804:
		return gbPropLV

	case r <= 53831:
		return gbPropLVT

	case r <= 53832:
		return gbPropLV

	case r <= 53859:
		return gbPropLVT

	case r <= 53860:
		return gbPropLV

	case r <= 53887:
		return gbPropLVT

	case r <= 53888:
		return gbPropLV

	case r <= 53915:
		return gbPropLVT

	case r <= 53916:
		return gbPropLV

	case r <= 53943:
		return gbPropLVT

	case r <= 53944:
		return gbPropLV

	case r <= 53971:
		return gbPropLVT

	case r <= 53972:
		return gbPropLV

	case r <= 53999:
		return gbPropLVT

	case r <= 54000:
		return gbPropLV

	case r <= 54027:
		return gbPropLVT

	case r <= 54028:
		return gbPropLV

	case r <= 54055:
		return gbPropLVT

	case r <= 54056:
		return gbPropLV

	case r <= 54083:
		return gbPropLVT

	case r <= 54084:
		return gbPropLV

	case r <= 54111:
		return gbPropLVT

	case r <= 54112:
		return gbPropLV

	case r <= 54139:
		return gbPropLVT

	case r <= 54140:
		return gbPropLV

	case r <= 54167:
		return gbPropLVT

	case r <= 54168:
		return gbPropLV

	case r <= 54195:
		return gbPropLVT

	case r <= 54196:
		return gbPropLV

	case r <= 54223:
		return gbPropLVT

	case r <= 54224:
		return gbPropLV

	case r <= 54251:
		return gbPropLVT

	case r <= 54252:
		return gbPropLV

	case r <= 54279:
		return gbPropLVT

	case r <= 54280:
		return gbPropLV

	case r <= 54307:
		return gbPropLVT

	case r <= 54308:
		return gbPropLV

	case r <= 54335:
		return gbPropLVT

	case r <= 54336:
		return gbPropLV

	case r <= 54363:
		return gbPropLVT

	case r <= 54364:
		return gbPropLV

	case r <= 54391:
		return gbPropLVT

	case r <= 54392:
		return gbPropLV

	case r <= 54419:
		return gbPropLVT

	case r <= 54420:
		return gbPropLV

	case r <= 54447:
		return gbPropLVT

	case r <= 54448:
		return gbPropLV

	case r <= 54475:
		return gbPropLVT

	case r <= 54476:
		return gbPropLV

	case r <= 54503:
		return gbPropLVT

	case r <= 54504:
		return gbPropLV

	case r <= 54531:
		return gbPropLVT

	case r <= 54532:
		return gbPropLV

	case r <= 54559:
		return gbPropLVT

	case r <= 54560:
		return gbPropLV

	case r <= 54587:
		return gbPropLVT

	case r <= 54588:
		return gbPropLV

	case r <= 54615:
		return gbPropLVT

	case r <= 54616:
		return gbPropLV

	case r <= 54643:
		return gbPropLVT

	case r <= 54644:
		return gbPropLV

	case r <= 54671:
		return gbPropLVT

	case r <= 54672:
		return gbPropLV

	case r <= 54699:
		return gbPropLVT

	case r <= 54700:
		return gbPropLV

	case r <= 54727:
		return gbPropLVT

	case r <= 54728:
		return gbPropLV

	case r <= 54755:
		return gbPropLVT

	case r <= 54756:
		return gbPropLV

	case r <= 54783:
		return gbPropLVT

	case r <= 54784:
		return gbPropLV

	case r <= 54811:
		return gbPropLVT

	case r <= 54812:
		return gbPropLV

	case r <= 54839:
		return gbPropLVT

	case r <= 54840:
		return gbPropLV

	case r <= 54867:
		return gbPropLVT

	case r <= 54868:
		return gbPropLV

	case r <= 54895:
		return gbPropLVT

	case r <= 54896:
		return gbPropLV

	case r <= 54923:
		return gbPropLVT

	case r <= 54924:
		return gbPropLV

	case r <= 54951:
		return gbPropLVT

	case r <= 54952:
		return gbPropLV

	case r <= 54979:
		return gbPropLVT

	case r <= 54980:
		return gbPropLV

	case r <= 55007:
		return gbPropLVT

	case r <= 55008:
		return gbPropLV

	case r <= 55035:
		return gbPropLVT

	case r <= 55036:
		return gbPropLV

	case r <= 55063:
		return gbPropLVT

	case r <= 55064:
		return gbPropLV

	case r <= 55091:
		return gbPropLVT

	case r <= 55092:
		return gbPropLV

	case r <= 55119:
		return gbPropLVT

	case r <= 55120:
		return gbPropLV

	case r <= 55147:
		return gbPropLVT

	case r <= 55148:
		return gbPropLV

	case r <= 55175:
		return gbPropLVT

	case r <= 55176:
		return gbPropLV

	case r <= 55203:
		return gbPropLVT

	case r <= 55215:
		return gbPropOther

	case r <= 55238:
		return gbPropV

	case r <= 55242:
		return gbPropOther

	case r <= 55291:
		return gbPropT

	case r <= 64285:
		return gbPropOther

	case r <= 64286:
		return gbPropExtend

	case r <= 65023:
		return gbPropOther

	case r <= 65039:
		return gbPropExtend

	case r <= 65055:
		return gbPropOther

	case r <= 65071:
		return gbPropExtend

	case r <= 65278:
		return gbPropOther

	case r <= 65279:
		return gbPropControl

	case r <= 65437:
		return gbPropOther

	case r <= 65439:
		return gbPropExtend

	case r <= 65519:
		return gbPropOther

	case r <= 65528:
		return gbPropControl

	case r <= 65531:
		return gbPropControl

	case r <= 66044:
		return gbPropOther

	case r <= 66045:
		return gbPropExtend

	case r <= 66271:
		return gbPropOther

	case r <= 66272:
		return gbPropExtend

	case r <= 66421:
		return gbPropOther

	case r <= 66426:
		return gbPropExtend

	case r <= 68096:
		return gbPropOther

	case r <= 68099:
		return gbPropExtend

	case r <= 68100:
		return gbPropOther

	case r <= 68102:
		return gbPropExtend

	case r <= 68107:
		return gbPropOther

	case r <= 68111:
		return gbPropExtend

	case r <= 68151:
		return gbPropOther

	case r <= 68154:
		return gbPropExtend

	case r <= 68158:
		return gbPropOther

	case r <= 68159:
		return gbPropExtend

	case r <= 68324:
		return gbPropOther

	case r <= 68326:
		return gbPropExtend

	case r <= 68899:
		return gbPropOther

	case r <= 68903:
		return gbPropExtend

	case r <= 69290:
		return gbPropOther

	case r <= 69292:
		return gbPropExtend

	case r <= 69445:
		return gbPropOther

	case r <= 69456:
		return gbPropExtend

	case r <= 69631:
		return gbPropOther

	case r <= 69632:
		return gbPropSpacingMark

	case r <= 69633:
		return gbPropExtend

	case r <= 69634:
		return gbPropSpacingMark

	case r <= 69687:
		return gbPropOther

	case r <= 69702:
		return gbPropExtend

	case r <= 69758:
		return gbPropOther

	case r <= 69761:
		return gbPropExtend

	case r <= 69762:
		return gbPropSpacingMark

	case r <= 69807:
		return gbPropOther

	case r <= 69810:
		return gbPropSpacingMark

	case r <= 69814:
		return gbPropExtend

	case r <= 69816:
		return gbPropSpacingMark

	case r <= 69818:
		return gbPropExtend

	case r <= 69820:
		return gbPropOther

	case r <= 69821:
		return gbPropPrepend

	case r <= 69836:
		return gbPropOther

	case r <= 69837:
		return gbPropPrepend

	case r <= 69887:
		return gbPropOther

	case r <= 69890:
		return gbPropExtend

	case r <= 69926:
		return gbPropOther

	case r <= 69931:
		return gbPropExtend

	case r <= 69932:
		return gbPropSpacingMark

	case r <= 69940:
		return gbPropExtend

	case r <= 69956:
		return gbPropOther

	case r <= 69958:
		return gbPropSpacingMark

	case r <= 70002:
		return gbPropOther

	case r <= 70003:
		return gbPropExtend

	case r <= 70015:
		return gbPropOther

	case r <= 70017:
		return gbPropExtend

	case r <= 70018:
		return gbPropSpacingMark

	case r <= 70066:
		return gbPropOther

	case r <= 70069:
		return gbPropSpacingMark

	case r <= 70078:
		return gbPropExtend

	case r <= 70080:
		return gbPropSpacingMark

	case r <= 70081:
		return gbPropOther

	case r <= 70083:
		return gbPropPrepend

	case r <= 70088:
		return gbPropOther

	case r <= 70092:
		return gbPropExtend

	case r <= 70093:
		return gbPropOther

	case r <= 70094:
		return gbPropSpacingMark

	case r <= 70095:
		return gbPropExtend

	case r <= 70187:
		return gbPropOther

	case r <= 70190:
		return gbPropSpacingMark

	case r <= 70193:
		return gbPropExtend

	case r <= 70195:
		return gbPropSpacingMark

	case r <= 70196:
		return gbPropExtend

	case r <= 70197:
		return gbPropSpacingMark

	case r <= 70199:
		return gbPropExtend

	case r <= 70205:
		return gbPropOther

	case r <= 70206:
		return gbPropExtend

	case r <= 70366:
		return gbPropOther

	case r <= 70367:
		return gbPropExtend

	case r <= 70370:
		return gbPropSpacingMark

	case r <= 70378:
		return gbPropExtend

	case r <= 70399:
		return gbPropOther

	case r <= 70401:
		return gbPropExtend

	case r <= 70403:
		return gbPropSpacingMark

	case r <= 70458:
		return gbPropOther

	case r <= 70460:
		return gbPropExtend

	case r <= 70461:
		return gbPropOther

	case r <= 70462:
		return gbPropExtend

	case r <= 70463:
		return gbPropSpacingMark

	case r <= 70464:
		return gbPropExtend

	case r <= 70468:
		return gbPropSpacingMark

	case r <= 70470:
		return gbPropOther

	case r <= 70472:
		return gbPropSpacingMark

	case r <= 70474:
		return gbPropOther

	case r <= 70477:
		return gbPropSpacingMark

	case r <= 70486:
		return gbPropOther

	case r <= 70487:
		return gbPropExtend

	case r <= 70497:
		return gbPropOther

	case r <= 70499:
		return gbPropSpacingMark

	case r <= 70501:
		return gbPropOther

	case r <= 70508:
		return gbPropExtend

	case r <= 70511:
		return gbPropOther

	case r <= 70516:
		return gbPropExtend

	case r <= 70708:
		return gbPropOther

	case r <= 70711:
		return gbPropSpacingMark

	case r <= 70719:
		return gbPropExtend

	case r <= 70721:
		return gbPropSpacingMark

	case r <= 70724:
		return gbPropExtend

	case r <= 70725:
		return gbPropSpacingMark

	case r <= 70726:
		return gbPropExtend

	case r <= 70749:
		return gbPropOther

	case r <= 70750:
		return gbPropExtend

	case r <= 70831:
		return gbPropOther

	case r <= 70832:
		return gbPropExtend

	case r <= 70834:
		return gbPropSpacingMark

	case r <= 70840:
		return gbPropExtend

	case r <= 70841:
		return gbPropSpacingMark

	case r <= 70842:
		return gbPropExtend

	case r <= 70844:
		return gbPropSpacingMark

	case r <= 70845:
		return gbPropExtend

	case r <= 70846:
		return gbPropSpacingMark

	case r <= 70848:
		return gbPropExtend

	case r <= 70849:
		return gbPropSpacingMark

	case r <= 70851:
		return gbPropExtend

	case r <= 71086:
		return gbPropOther

	case r <= 71087:
		return gbPropExtend

	case r <= 71089:
		return gbPropSpacingMark

	case r <= 71093:
		return gbPropExtend

	case r <= 71095:
		return gbPropOther

	case r <= 71099:
		return gbPropSpacingMark

	case r <= 71101:
		return gbPropExtend

	case r <= 71102:
		return gbPropSpacingMark

	case r <= 71104:
		return gbPropExtend

	case r <= 71131:
		return gbPropOther

	case r <= 71133:
		return gbPropExtend

	case r <= 71215:
		return gbPropOther

	case r <= 71218:
		return gbPropSpacingMark

	case r <= 71226:
		return gbPropExtend

	case r <= 71228:
		return gbPropSpacingMark

	case r <= 71229:
		return gbPropExtend

	case r <= 71230:
		return gbPropSpacingMark

	case r <= 71232:
		return gbPropExtend

	case r <= 71338:
		return gbPropOther

	case r <= 71339:
		return gbPropExtend

	case r <= 71340:
		return gbPropSpacingMark

	case r <= 71341:
		return gbPropExtend

	case r <= 71343:
		return gbPropSpacingMark

	case r <= 71349:
		return gbPropExtend

	case r <= 71350:
		return gbPropSpacingMark

	case r <= 71351:
		return gbPropExtend

	case r <= 71452:
		return gbPropOther

	case r <= 71455:
		return gbPropExtend

	case r <= 71457:
		return gbPropSpacingMark

	case r <= 71461:
		return gbPropExtend

	case r <= 71462:
		return gbPropSpacingMark

	case r <= 71467:
		return gbPropExtend

	case r <= 71723:
		return gbPropOther

	case r <= 71726:
		return gbPropSpacingMark

	case r <= 71735:
		return gbPropExtend

	case r <= 71736:
		return gbPropSpacingMark

	case r <= 71738:
		return gbPropExtend

	case r <= 71983:
		return gbPropOther

	case r <= 71984:
		return gbPropExtend

	case r <= 71989:
		return gbPropSpacingMark

	case r <= 71990:
		return gbPropOther

	case r <= 71992:
		return gbPropSpacingMark

	case r <= 71994:
		return gbPropOther

	case r <= 71996:
		return gbPropExtend

	case r <= 71997:
		return gbPropSpacingMark

	case r <= 71998:
		return gbPropExtend

	case r <= 71999:
		return gbPropPrepend

	case r <= 72000:
		return gbPropSpacingMark

	case r <= 72001:
		return gbPropPrepend

	case r <= 72002:
		return gbPropSpacingMark

	case r <= 72003:
		return gbPropExtend

	case r <= 72144:
		return gbPropOther

	case r <= 72147:
		return gbPropSpacingMark

	case r <= 72151:
		return gbPropExtend

	case r <= 72153:
		return gbPropOther

	case r <= 72155:
		return gbPropExtend

	case r <= 72159:
		return gbPropSpacingMark

	case r <= 72160:
		return gbPropExtend

	case r <= 72163:
		return gbPropOther

	case r <= 72164:
		return gbPropSpacingMark

	case r <= 72192:
		return gbPropOther

	case r <= 72202:
		return gbPropExtend

	case r <= 72242:
		return gbPropOther

	case r <= 72248:
		return gbPropExtend

	case r <= 72249:
		return gbPropSpacingMark

	case r <= 72250:
		return gbPropPrepend

	case r <= 72254:
		return gbPropExtend

	case r <= 72262:
		return gbPropOther

	case r <= 72263:
		return gbPropExtend

	case r <= 72272:
		return gbPropOther

	case r <= 72278:
		return gbPropExtend

	case r <= 72280:
		return gbPropSpacingMark

	case r <= 72283:
		return gbPropExtend

	case r <= 72323:
		return gbPropOther

	case r <= 72329:
		return gbPropPrepend

	case r <= 72342:
		return gbPropExtend

	case r <= 72343:
		return gbPropSpacingMark

	case r <= 72345:
		return gbPropExtend

	case r <= 72750:
		return gbPropOther

	case r <= 72751:
		return gbPropSpacingMark

	case r <= 72758:
		return gbPropExtend

	case r <= 72759:
		return gbPropOther

	case r <= 72765:
		return gbPropExtend

	case r <= 72766:
		return gbPropSpacingMark

	case r <= 72767:
		return gbPropExtend

	case r <= 72849:
		return gbPropOther

	case r <= 72871:
		return gbPropExtend

	case r <= 72872:
		return gbPropOther

	case r <= 72873:
		return gbPropSpacingMark

	case r <= 72880:
		return gbPropExtend

	case r <= 72881:
		return gbPropSpacingMark

	case r <= 72883:
		return gbPropExtend

	case r <= 72884:
		return gbPropSpacingMark

	case r <= 72886:
		return gbPropExtend

	case r <= 73008:
		return gbPropOther

	case r <= 73014:
		return gbPropExtend

	case r <= 73017:
		return gbPropOther

	case r <= 73018:
		return gbPropExtend

	case r <= 73019:
		return gbPropOther

	case r <= 73021:
		return gbPropExtend

	case r <= 73022:
		return gbPropOther

	case r <= 73029:
		return gbPropExtend

	case r <= 73030:
		return gbPropPrepend

	case r <= 73031:
		return gbPropExtend

	case r <= 73097:
		return gbPropOther

	case r <= 73102:
		return gbPropSpacingMark

	case r <= 73103:
		return gbPropOther

	case r <= 73105:
		return gbPropExtend

	case r <= 73106:
		return gbPropOther

	case r <= 73108:
		return gbPropSpacingMark

	case r <= 73109:
		return gbPropExtend

	case r <= 73110:
		return gbPropSpacingMark

	case r <= 73111:
		return gbPropExtend

	case r <= 73458:
		return gbPropOther

	case r <= 73460:
		return gbPropExtend

	case r <= 73462:
		return gbPropSpacingMark

	case r <= 78895:
		return gbPropOther

	case r <= 78904:
		return gbPropControl

	case r <= 92911:
		return gbPropOther

	case r <= 92916:
		return gbPropExtend

	case r <= 92975:
		return gbPropOther

	case r <= 92982:
		return gbPropExtend

	case r <= 94030:
		return gbPropOther

	case r <= 94031:
		return gbPropExtend

	case r <= 94032:
		return gbPropOther

	case r <= 94087:
		return gbPropSpacingMark

	case r <= 94094:
		return gbPropOther

	case r <= 94098:
		return gbPropExtend

	case r <= 94179:
		return gbPropOther

	case r <= 94180:
		return gbPropExtend

	case r <= 94191:
		return gbPropOther

	case r <= 94193:
		return gbPropSpacingMark

	case r <= 113820:
		return gbPropOther

	case r <= 113822:
		return gbPropExtend

	case r <= 113823:
		return gbPropOther

	case r <= 113827:
		return gbPropControl

	case r <= 119140:
		return gbPropOther

	case r <= 119141:
		return gbPropExtend

	case r <= 119142:
		return gbPropSpacingMark

	case r <= 119145:
		return gbPropExtend

	case r <= 119148:
		return gbPropOther

	case r <= 119149:
		return gbPropSpacingMark

	case r <= 119154:
		return gbPropExtend

	case r <= 119162:
		return gbPropControl

	case r <= 119170:
		return gbPropExtend

	case r <= 119172:
		return gbPropOther

	case r <= 119179:
		return gbPropExtend

	case r <= 119209:
		return gbPropOther

	case r <= 119213:
		return gbPropExtend

	case r <= 119361:
		return gbPropOther

	case r <= 119364:
		return gbPropExtend

	case r <= 121343:
		return gbPropOther

	case r <= 121398:
		return gbPropExtend

	case r <= 121402:
		return gbPropOther

	case r <= 121452:
		return gbPropExtend

	case r <= 121460:
		return gbPropOther

	case r <= 121461:
		return gbPropExtend

	case r <= 121475:
		return gbPropOther

	case r <= 121476:
		return gbPropExtend

	case r <= 121498:
		return gbPropOther

	case r <= 121503:
		return gbPropExtend

	case r <= 121504:
		return gbPropOther

	case r <= 121519:
		return gbPropExtend

	case r <= 122879:
		return gbPropOther

	case r <= 122886:
		return gbPropExtend

	case r <= 122887:
		return gbPropOther

	case r <= 122904:
		return gbPropExtend

	case r <= 122906:
		return gbPropOther

	case r <= 122913:
		return gbPropExtend

	case r <= 122914:
		return gbPropOther

	case r <= 122916:
		return gbPropExtend

	case r <= 122917:
		return gbPropOther

	case r <= 122922:
		return gbPropExtend

	case r <= 123183:
		return gbPropOther

	case r <= 123190:
		return gbPropExtend

	case r <= 123627:
		return gbPropOther

	case r <= 123631:
		return gbPropExtend

	case r <= 125135:
		return gbPropOther

	case r <= 125142:
		return gbPropExtend

	case r <= 125251:
		return gbPropOther

	case r <= 125258:
		return gbPropExtend

	case r <= 126975:
		return gbPropOther

	case r <= 126979:
		return gbPropExtended_Pictographic

	case r <= 126980:
		return gbPropExtended_Pictographic

	case r <= 127182:
		return gbPropExtended_Pictographic

	case r <= 127183:
		return gbPropExtended_Pictographic

	case r <= 127231:
		return gbPropExtended_Pictographic

	case r <= 127244:
		return gbPropOther

	case r <= 127247:
		return gbPropExtended_Pictographic

	case r <= 127278:
		return gbPropOther

	case r <= 127279:
		return gbPropExtended_Pictographic

	case r <= 127339:
		return gbPropOther

	case r <= 127343:
		return gbPropExtended_Pictographic

	case r <= 127345:
		return gbPropExtended_Pictographic

	case r <= 127357:
		return gbPropOther

	case r <= 127359:
		return gbPropExtended_Pictographic

	case r <= 127373:
		return gbPropOther

	case r <= 127374:
		return gbPropExtended_Pictographic

	case r <= 127376:
		return gbPropOther

	case r <= 127386:
		return gbPropExtended_Pictographic

	case r <= 127404:
		return gbPropOther

	case r <= 127461:
		return gbPropExtended_Pictographic

	case r <= 127487:
		return gbPropRegional_Indicator

	case r <= 127488:
		return gbPropOther

	case r <= 127490:
		return gbPropExtended_Pictographic

	case r <= 127503:
		return gbPropExtended_Pictographic

	case r <= 127513:
		return gbPropOther

	case r <= 127514:
		return gbPropExtended_Pictographic

	case r <= 127534:
		return gbPropOther

	case r <= 127535:
		return gbPropExtended_Pictographic

	case r <= 127537:
		return gbPropOther

	case r <= 127546:
		return gbPropExtended_Pictographic

	case r <= 127547:
		return gbPropOther

	case r <= 127551:
		return gbPropExtended_Pictographic

	case r <= 127560:
		return gbPropOther

	case r <= 127567:
		return gbPropExtended_Pictographic

	case r <= 127569:
		return gbPropExtended_Pictographic

	case r <= 127743:
		return gbPropExtended_Pictographic

	case r <= 127777:
		return gbPropExtended_Pictographic

	case r <= 127779:
		return gbPropExtended_Pictographic

	case r <= 127891:
		return gbPropExtended_Pictographic

	case r <= 127893:
		return gbPropExtended_Pictographic

	case r <= 127895:
		return gbPropExtended_Pictographic

	case r <= 127896:
		return gbPropExtended_Pictographic

	case r <= 127899:
		return gbPropExtended_Pictographic

	case r <= 127901:
		return gbPropExtended_Pictographic

	case r <= 127984:
		return gbPropExtended_Pictographic

	case r <= 127986:
		return gbPropExtended_Pictographic

	case r <= 127989:
		return gbPropExtended_Pictographic

	case r <= 127990:
		return gbPropExtended_Pictographic

	case r <= 127994:
		return gbPropExtended_Pictographic

	case r <= 127999:
		return gbPropExtend

	case r <= 128253:
		return gbPropExtended_Pictographic

	case r <= 128254:
		return gbPropExtended_Pictographic

	case r <= 128317:
		return gbPropExtended_Pictographic

	case r <= 128325:
		return gbPropOther

	case r <= 128328:
		return gbPropExtended_Pictographic

	case r <= 128334:
		return gbPropExtended_Pictographic

	case r <= 128335:
		return gbPropExtended_Pictographic

	case r <= 128359:
		return gbPropExtended_Pictographic

	case r <= 128366:
		return gbPropExtended_Pictographic

	case r <= 128368:
		return gbPropExtended_Pictographic

	case r <= 128370:
		return gbPropExtended_Pictographic

	case r <= 128377:
		return gbPropExtended_Pictographic

	case r <= 128378:
		return gbPropExtended_Pictographic

	case r <= 128390:
		return gbPropExtended_Pictographic

	case r <= 128391:
		return gbPropExtended_Pictographic

	case r <= 128393:
		return gbPropExtended_Pictographic

	case r <= 128397:
		return gbPropExtended_Pictographic

	case r <= 128399:
		return gbPropExtended_Pictographic

	case r <= 128400:
		return gbPropExtended_Pictographic

	case r <= 128404:
		return gbPropExtended_Pictographic

	case r <= 128406:
		return gbPropExtended_Pictographic

	case r <= 128419:
		return gbPropExtended_Pictographic

	case r <= 128420:
		return gbPropExtended_Pictographic

	case r <= 128421:
		return gbPropExtended_Pictographic

	case r <= 128423:
		return gbPropExtended_Pictographic

	case r <= 128424:
		return gbPropExtended_Pictographic

	case r <= 128432:
		return gbPropExtended_Pictographic

	case r <= 128434:
		return gbPropExtended_Pictographic

	case r <= 128443:
		return gbPropExtended_Pictographic

	case r <= 128444:
		return gbPropExtended_Pictographic

	case r <= 128449:
		return gbPropExtended_Pictographic

	case r <= 128452:
		return gbPropExtended_Pictographic

	case r <= 128464:
		return gbPropExtended_Pictographic

	case r <= 128467:
		return gbPropExtended_Pictographic

	case r <= 128475:
		return gbPropExtended_Pictographic

	case r <= 128478:
		return gbPropExtended_Pictographic

	case r <= 128480:
		return gbPropExtended_Pictographic

	case r <= 128481:
		return gbPropExtended_Pictographic

	case r <= 128482:
		return gbPropExtended_Pictographic

	case r <= 128483:
		return gbPropExtended_Pictographic

	case r <= 128487:
		return gbPropExtended_Pictographic

	case r <= 128488:
		return gbPropExtended_Pictographic

	case r <= 128494:
		return gbPropExtended_Pictographic

	case r <= 128495:
		return gbPropExtended_Pictographic

	case r <= 128498:
		return gbPropExtended_Pictographic

	case r <= 128499:
		return gbPropExtended_Pictographic

	case r <= 128505:
		return gbPropExtended_Pictographic

	case r <= 128591:
		return gbPropExtended_Pictographic

	case r <= 128639:
		return gbPropOther

	case r <= 128709:
		return gbPropExtended_Pictographic

	case r <= 128714:
		return gbPropExtended_Pictographic

	case r <= 128720:
		return gbPropExtended_Pictographic

	case r <= 128722:
		return gbPropExtended_Pictographic

	case r <= 128724:
		return gbPropExtended_Pictographic

	case r <= 128725:
		return gbPropExtended_Pictographic

	case r <= 128735:
		return gbPropExtended_Pictographic

	case r <= 128741:
		return gbPropExtended_Pictographic

	case r <= 128744:
		return gbPropExtended_Pictographic

	case r <= 128745:
		return gbPropExtended_Pictographic

	case r <= 128746:
		return gbPropExtended_Pictographic

	case r <= 128748:
		return gbPropExtended_Pictographic

	case r <= 128751:
		return gbPropExtended_Pictographic

	case r <= 128752:
		return gbPropExtended_Pictographic

	case r <= 128754:
		return gbPropExtended_Pictographic

	case r <= 128755:
		return gbPropExtended_Pictographic

	case r <= 128758:
		return gbPropExtended_Pictographic

	case r <= 128760:
		return gbPropExtended_Pictographic

	case r <= 128761:
		return gbPropExtended_Pictographic

	case r <= 128762:
		return gbPropExtended_Pictographic

	case r <= 128767:
		return gbPropExtended_Pictographic

	case r <= 128883:
		return gbPropOther

	case r <= 128895:
		return gbPropExtended_Pictographic

	case r <= 128980:
		return gbPropOther

	case r <= 128991:
		return gbPropExtended_Pictographic

	case r <= 129003:
		return gbPropExtended_Pictographic

	case r <= 129023:
		return gbPropExtended_Pictographic

	case r <= 129035:
		return gbPropOther

	case r <= 129039:
		return gbPropExtended_Pictographic

	case r <= 129095:
		return gbPropOther

	case r <= 129103:
		return gbPropExtended_Pictographic

	case r <= 129113:
		return gbPropOther

	case r <= 129119:
		return gbPropExtended_Pictographic

	case r <= 129159:
		return gbPropOther

	case r <= 129167:
		return gbPropExtended_Pictographic

	case r <= 129197:
		return gbPropOther

	case r <= 129279:
		return gbPropExtended_Pictographic

	case r <= 129291:
		return gbPropOther

	case r <= 129292:
		return gbPropExtended_Pictographic

	case r <= 129295:
		return gbPropExtended_Pictographic

	case r <= 129304:
		return gbPropExtended_Pictographic

	case r <= 129310:
		return gbPropExtended_Pictographic

	case r <= 129311:
		return gbPropExtended_Pictographic

	case r <= 129319:
		return gbPropExtended_Pictographic

	case r <= 129327:
		return gbPropExtended_Pictographic

	case r <= 129328:
		return gbPropExtended_Pictographic

	case r <= 129330:
		return gbPropExtended_Pictographic

	case r <= 129338:
		return gbPropExtended_Pictographic

	case r <= 129339:
		return gbPropOther

	case r <= 129342:
		return gbPropExtended_Pictographic

	case r <= 129343:
		return gbPropExtended_Pictographic

	case r <= 129349:
		return gbPropExtended_Pictographic

	case r <= 129350:
		return gbPropOther

	case r <= 129355:
		return gbPropExtended_Pictographic

	case r <= 129356:
		return gbPropExtended_Pictographic

	case r <= 129359:
		return gbPropExtended_Pictographic

	case r <= 129374:
		return gbPropExtended_Pictographic

	case r <= 129387:
		return gbPropExtended_Pictographic

	case r <= 129392:
		return gbPropExtended_Pictographic

	case r <= 129393:
		return gbPropExtended_Pictographic

	case r <= 129394:
		return gbPropExtended_Pictographic

	case r <= 129398:
		return gbPropExtended_Pictographic

	case r <= 129401:
		return gbPropExtended_Pictographic

	case r <= 129402:
		return gbPropExtended_Pictographic

	case r <= 129403:
		return gbPropExtended_Pictographic

	case r <= 129407:
		return gbPropExtended_Pictographic

	case r <= 129412:
		return gbPropExtended_Pictographic

	case r <= 129425:
		return gbPropExtended_Pictographic

	case r <= 129431:
		return gbPropExtended_Pictographic

	case r <= 129442:
		return gbPropExtended_Pictographic

	case r <= 129444:
		return gbPropExtended_Pictographic

	case r <= 129450:
		return gbPropExtended_Pictographic

	case r <= 129453:
		return gbPropExtended_Pictographic

	case r <= 129455:
		return gbPropExtended_Pictographic

	case r <= 129465:
		return gbPropExtended_Pictographic

	case r <= 129471:
		return gbPropExtended_Pictographic

	case r <= 129472:
		return gbPropExtended_Pictographic

	case r <= 129474:
		return gbPropExtended_Pictographic

	case r <= 129482:
		return gbPropExtended_Pictographic

	case r <= 129484:
		return gbPropExtended_Pictographic

	case r <= 129487:
		return gbPropExtended_Pictographic

	case r <= 129510:
		return gbPropExtended_Pictographic

	case r <= 129535:
		return gbPropExtended_Pictographic

	case r <= 129647:
		return gbPropExtended_Pictographic

	case r <= 129651:
		return gbPropExtended_Pictographic

	case r <= 129655:
		return gbPropExtended_Pictographic

	case r <= 129658:
		return gbPropExtended_Pictographic

	case r <= 129663:
		return gbPropExtended_Pictographic

	case r <= 129666:
		return gbPropExtended_Pictographic

	case r <= 129679:
		return gbPropExtended_Pictographic

	case r <= 129685:
		return gbPropExtended_Pictographic

	case r <= 131069:
		return gbPropExtended_Pictographic

	case r <= 917503:
		return gbPropOther

	case r <= 917504:
		return gbPropControl

	case r <= 917505:
		return gbPropControl

	case r <= 917535:
		return gbPropControl

	case r <= 917631:
		return gbPropExtend

	case r <= 917759:
		return gbPropControl

	case r <= 917999:
		return gbPropExtend

	case r <= 921599:
		return gbPropControl

	default:
		return gbPropOther
	}
}
