// This file is generated by gen_tokenizers.go.  DO NOT EDIT.
package syntax

import (
	"log"

	"github.com/aretext/aretext/syntax/parser"
)

// Language is an enum of available languages that we can parse.
type Language int

const (
	LanguageUndefined = Language(iota)
	LanguagePlaintext
	LanguageJson
	LanguageYaml
	LanguageGo
)

var AllLanguages = []Language{
	LanguagePlaintext,
	LanguageJson,
	LanguageYaml,
	LanguageGo,
}

func (language Language) String() string {
	switch language {
	case LanguageUndefined:
		return "undefined"
	case LanguagePlaintext:
		return "plaintext"
	case LanguageJson:
		return "json"
	case LanguageYaml:
		return "yaml"
	case LanguageGo:
		return "go"
	default:
		return ""
	}
}

func LanguageFromString(s string) Language {
	switch s {
	case "undefined":
		return LanguageUndefined
	case "plaintext":
		return LanguagePlaintext
	case "json":
		return LanguageJson
	case "yaml":
		return LanguageYaml
	case "go":
		return LanguageGo
	default:
		log.Printf("Unrecognized syntax language '%s'\n", s)
		return LanguageUndefined
	}
}

// TokenizerForLanguage returns a tokenizer for the specified language.
// If no tokenizer is available (e.g. for LanguageUndefined), this returns nil.
func TokenizerForLanguage(language Language) *parser.Tokenizer {
	switch language {
	case LanguagePlaintext:
		return PlaintextTokenizer
	case LanguageJson:
		return JsonTokenizer
	case LanguageYaml:
		return YamlTokenizer
	case LanguageGo:
		return GoTokenizer
	default:
		return nil
	}
}
