// This file is generated by gen.go.  DO NOT EDIT.

package rpc

// A message with no fields.
type EmptyMsg struct {
}

// Parameters for setting the syntax of the current document
type SetSyntaxMsg struct {

	// Language of the syntax
	Language string `json:"language"`
}

// Parameters for profiling memory
type ProfileMemoryMsg struct {

	// Path of the file where the memory profile will be written
	Path string `json:"path"`
}

// A message describing the result of a memory profile
type OpResultMsg struct {

	// Whether the operation completed successfully
	Success bool `json:"success"`

	// A description of the operation's result
	Description string `json:"description"`
}
