// This file is generated by gen.go.  DO NOT EDIT.

package rpc

// A message with no fields.
type EmptyMsg struct {
}

// A message describing where to write the memory profile
type ProfileMemoryRequestMsg struct {

	// Path of the file where the memory profile will be written
	Path string `json:"path"`
}

// A message describing the result of a memory profile
type ProfileMemoryResponseMsg struct {

	// Whether the memory profile was written successfully
	Succeeded bool `json:"succeeded"`

	// The reason why the memory profile failed
	Error string `json:"error"`
}

// A message describing the result of a quit request.
type QuitResultMsg struct {

	// Whether the quit request was accepted.
	Accepted bool `json:"accepted"`

	// The reason the quit request was rejected.
	RejectReason string `json:"reject_reason"`
}
