// This file is generated by gen.go.  DO NOT EDIT.

package rpc

// A message with no fields.
type EmptyMsg struct {
}

// A message describing the result of a quit request.
type QuitResultMsg struct {

	// Whether the quit request was accepted.
	Accepted bool `json:"accepted"`

	// The reason the quit request was rejected.
	RejectReason string `json:"reject_reason"`
}
