name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install goimports
      run: go get golang.org/x/tools/cmd/goimports

    - name: Build and run tests
      run: make

    - name: Verify all changes committed (autoformat / generated code)
      run: |
        DIFF=$(git diff --numstat -- ':!go\.*')
        if [[ -n "$DIFF" ]]; then
            echo "Uncommitted changes detected:";
            echo "$DIFF";
            echo "To resolve, please run these commands:"
            echo "    make && git add . && git commit"
            exit 1;
        fi
