name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: Install dev tools
      run: make install-devtools

    - name: Build and run tests
      run: make

    - name: Verify all changes committed (autoformat / generated code)
      run: |
        DIFF=$(git diff --numstat -- ':!go\.*')
        if [[ -n "$DIFF" ]]; then
            echo "Uncommitted changes detected:";
            echo "$DIFF";
            echo "To resolve, please run these commands:"
            echo "    make && git add . && git commit"
            exit 1;
        fi
